// =============================================================================
// Generated by efx_ipmgr
// Version: 2025.2.288.4.15
// IP Version: 6.13
// =============================================================================

////////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2013-2025 Efinix Inc. All rights reserved.              
//
// This   document  contains  proprietary information  which   is        
// protected by  copyright. All rights  are reserved.  This notice       
// refers to original work by Efinix, Inc. which may be derivitive       
// of other work distributed under license of the authors.  In the       
// case of derivative work, nothing in this notice overrides the         
// original author's license agreement.  Where applicable, the           
// original license agreement is included in it's original               
// unmodified form immediately below this header.                        
//                                                                       
// WARRANTY DISCLAIMER.                                                  
//     THE  DESIGN, CODE, OR INFORMATION ARE PROVIDED “AS IS” AND        
//     EFINIX MAKES NO WARRANTIES, EXPRESS OR IMPLIED WITH               
//     RESPECT THERETO, AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES,  
//     INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF          
//     MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR    
//     PURPOSE.  SOME STATES DO NOT ALLOW EXCLUSIONS OF AN IMPLIED       
//     WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO LICENSEE.           
//                                                                       
// LIMITATION OF LIABILITY.                                              
//     NOTWITHSTANDING ANYTHING TO THE CONTRARY, EXCEPT FOR BODILY       
//     INJURY, EFINIX SHALL NOT BE LIABLE WITH RESPECT TO ANY SUBJECT    
//     MATTER OF THIS AGREEMENT UNDER TORT, CONTRACT, STRICT LIABILITY   
//     OR ANY OTHER LEGAL OR EQUITABLE THEORY (I) FOR ANY INDIRECT,      
//     SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY    
//     CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF      
//     GOODWILL, DATA OR PROFIT, WORK STOPPAGE, OR COMPUTER FAILURE OR   
//     MALFUNCTION, OR IN ANY EVENT (II) FOR ANY AMOUNT IN EXCESS, IN    
//     THE AGGREGATE, OF THE FEE PAID BY LICENSEE TO EFINIX HEREUNDER    
//     (OR, IF THE FEE HAS BEEN WAIVED, $100), EVEN IF EFINIX SHALL HAVE 
//     BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO 
//     NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR            
//     CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND EXCLUSION MAY NOT   
//     APPLY TO LICENSEE.                                                
//
////////////////////////////////////////////////////////////////////////////////

hyperram u_hyperram
(
    .ram_clk_cal ( ram_clk_cal ),
    .ram_clk ( ram_clk ),
    .rst ( rst ),
    .hbc_cal_pass ( hbc_cal_pass ),
    .hbc_ck_n_LO ( hbc_ck_n_LO ),
    .hbc_ck_n_HI ( hbc_ck_n_HI ),
    .hbc_ck_p_LO ( hbc_ck_p_LO ),
    .hbc_ck_p_HI ( hbc_ck_p_HI ),
    .hbc_cs_n ( hbc_cs_n ),
    .hbc_rst_n ( hbc_rst_n ),
    .hbc_cal_SHIFT_SEL ( hbc_cal_SHIFT_SEL ),
    .hbc_cal_SHIFT ( hbc_cal_SHIFT ),
    .hbc_cal_SHIFT_ENA ( hbc_cal_SHIFT_ENA ),
    .native_clk ( native_clk ),
    .native_ram_en ( native_ram_en ),
    .native_ram_address ( native_ram_address ),
    .native_ctrl_idle ( native_ctrl_idle ),
    .native_rd_valid ( native_rd_valid ),
    .native_wr_buf_ready ( native_wr_buf_ready ),
    .native_ram_burst_len ( native_ram_burst_len ),
    .native_wr_en ( native_wr_en ),
    .native_ram_rdwr ( native_ram_rdwr ),
    .hbc_dq_OE ( hbc_dq_OE ),
    .hbc_dq_IN_LO ( hbc_dq_IN_LO ),
    .hbc_dq_IN_HI ( hbc_dq_IN_HI ),
    .hbc_dq_OUT_LO ( hbc_dq_OUT_LO ),
    .hbc_dq_OUT_HI ( hbc_dq_OUT_HI ),
    .hbc_rwds_OE ( hbc_rwds_OE ),
    .hbc_rwds_IN_LO ( hbc_rwds_IN_LO ),
    .hbc_rwds_IN_HI ( hbc_rwds_IN_HI ),
    .hbc_rwds_OUT_LO ( hbc_rwds_OUT_LO ),
    .hbc_rwds_OUT_HI ( hbc_rwds_OUT_HI ),
    .native_wr_data ( native_wr_data ),
    .native_wr_datamask ( native_wr_datamask ),
    .native_rd_data ( native_rd_data ),
    .hbc_cal_debug_info ( hbc_cal_debug_info ),
    .dyn_pll_phase_sel ( dyn_pll_phase_sel ),
    .dyn_pll_phase_en ( dyn_pll_phase_en )
);
