
# Efinity Interface Designer SDC
# Version: 2023.M.238
# Date: 2023-09-27 17:30

# Copyright (C) 2017 - 2023 Efinix Inc. All rights reserved.

# Device: Ti60F100S3F2
# Project: hbram_ti60
# Timing Model: C4 (final)

# Oscillator Constraints
########################
create_clock -period 25 [get_ports {intosc_clkout}]

# PLL Constraints
#################
create_clock -period 5.0000 hbramClk
create_clock -waveform {1.2500 3.7500} -period 5.0000 hbramClk90
create_clock -period 5.0000 hbramClk_cal
create_clock -period 50.0000 clk0
create_clock -period 12.5000 clk_fb
create_clock -period 10.0000 clk
create_clock -period 10 [get_ports {jtag_inst1_TCK}]

# Clock Groups
##############
set_clock_groups -asynchronous -group {hbramClk hbramClk90} -group {hbramClk_cal} -group {intosc_clkout} -group {clk} -group {jtag_inst1_TCK}

# JTAG Constraints
####################
# create_clock -period <USER_PERIOD> [get_ports {jtag_inst1_TCK}]
set_output_delay -clock jtag_inst1_TCK -max 0.117 [get_ports {jtag_inst1_TDO}]
set_output_delay -clock jtag_inst1_TCK -min -0.075 [get_ports {jtag_inst1_TDO}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.280 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.187 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.280 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.187 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.243 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.162 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.280 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.187 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.337 [get_ports {jtag_inst1_SHIFT}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.225 [get_ports {jtag_inst1_SHIFT}]
# JTAG Constraints (extra... not used by current Efinity debug tools)
# create_clock -period <USER_PERIOD> [get_ports {jtag_inst1_DRCK}]
# set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.280 [get_ports {jtag_inst1_RUNTEST}]
# set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.187 [get_ports {jtag_inst1_RUNTEST}]
# Create separate clock groups for JTAG clocks. Remove DRCK clock from the list below if it is not defined.
# set_clock_groups -asynchronous -group {jtag_inst1_TCK jtag_inst1_DRCK}

# HSIO GPIO Constraints
#########################
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {io_asyncReset}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {io_asyncReset}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {hbc_cal_pass}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {hbc_cal_pass}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {test_fail}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {test_fail}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {test_good}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {test_good}]

# HyperRAM Constraints
########################
set_output_delay -clock_fall -clock hbramClk90 -reference_pin [get_ports {hbramClk90~CLKOUT~83~322}] -max 0.263 [get_ports {hbc_ck_n_LO hbc_ck_n_HI}]
set_output_delay -clock_fall -clock hbramClk90 -reference_pin [get_ports {hbramClk90~CLKOUT~83~322}] -min -0.140 [get_ports {hbc_ck_n_LO hbc_ck_n_HI}]
set_output_delay -clock_fall -clock hbramClk90 -reference_pin [get_ports {hbramClk90~CLKOUT~75~322}] -max 0.263 [get_ports {hbc_ck_p_LO hbc_ck_p_HI}]
set_output_delay -clock_fall -clock hbramClk90 -reference_pin [get_ports {hbramClk90~CLKOUT~75~322}] -min -0.140 [get_ports {hbc_ck_p_LO hbc_ck_p_HI}]
set_output_delay -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~122~322}] -max 0.263 [get_ports {hbc_cs_n}]
set_output_delay -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~122~322}] -min -0.140 [get_ports {hbc_cs_n}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {hbc_rst_n}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {hbc_rst_n}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~165~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[0] hbc_dq_IN_HI[0]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~165~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[0] hbc_dq_IN_HI[0]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~167~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[0] hbc_dq_OUT_HI[0]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~167~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[0] hbc_dq_OUT_HI[0]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~167~322}] -max 0.263 [get_ports {hbc_dq_OE[0]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~167~322}] -min -0.140 [get_ports {hbc_dq_OE[0]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~164~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[1] hbc_dq_IN_HI[1]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~164~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[1] hbc_dq_IN_HI[1]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~166~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[1] hbc_dq_OUT_HI[1]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~166~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[1] hbc_dq_OUT_HI[1]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~166~322}] -max 0.263 [get_ports {hbc_dq_OE[1]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~166~322}] -min -0.140 [get_ports {hbc_dq_OE[1]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~157~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[2] hbc_dq_IN_HI[2]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~157~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[2] hbc_dq_IN_HI[2]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~159~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[2] hbc_dq_OUT_HI[2]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~159~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[2] hbc_dq_OUT_HI[2]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~159~322}] -max 0.263 [get_ports {hbc_dq_OE[2]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~159~322}] -min -0.140 [get_ports {hbc_dq_OE[2]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~156~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[3] hbc_dq_IN_HI[3]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~156~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[3] hbc_dq_IN_HI[3]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~158~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[3] hbc_dq_OUT_HI[3]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~158~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[3] hbc_dq_OUT_HI[3]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~158~322}] -max 0.263 [get_ports {hbc_dq_OE[3]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~158~322}] -min -0.140 [get_ports {hbc_dq_OE[3]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~149~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[4] hbc_dq_IN_HI[4]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~149~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[4] hbc_dq_IN_HI[4]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~151~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[4] hbc_dq_OUT_HI[4]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~151~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[4] hbc_dq_OUT_HI[4]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~151~322}] -max 0.263 [get_ports {hbc_dq_OE[4]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~151~322}] -min -0.140 [get_ports {hbc_dq_OE[4]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~148~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[5] hbc_dq_IN_HI[5]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~148~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[5] hbc_dq_IN_HI[5]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~150~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[5] hbc_dq_OUT_HI[5]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~150~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[5] hbc_dq_OUT_HI[5]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~150~322}] -max 0.263 [get_ports {hbc_dq_OE[5]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~150~322}] -min -0.140 [get_ports {hbc_dq_OE[5]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~141~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[6] hbc_dq_IN_HI[6]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~141~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[6] hbc_dq_IN_HI[6]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~143~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[6] hbc_dq_OUT_HI[6]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~143~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[6] hbc_dq_OUT_HI[6]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~143~322}] -max 0.263 [get_ports {hbc_dq_OE[6]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~143~322}] -min -0.140 [get_ports {hbc_dq_OE[6]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~140~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[7] hbc_dq_IN_HI[7]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~140~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[7] hbc_dq_IN_HI[7]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~142~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[7] hbc_dq_OUT_HI[7]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~142~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[7] hbc_dq_OUT_HI[7]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~142~322}] -max 0.263 [get_ports {hbc_dq_OE[7]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~142~322}] -min -0.140 [get_ports {hbc_dq_OE[7]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~65~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[8] hbc_dq_IN_HI[8]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~65~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[8] hbc_dq_IN_HI[8]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~67~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[8] hbc_dq_OUT_HI[8]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~67~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[8] hbc_dq_OUT_HI[8]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~67~322}] -max 0.263 [get_ports {hbc_dq_OE[8]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~67~322}] -min -0.140 [get_ports {hbc_dq_OE[8]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~64~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[9] hbc_dq_IN_HI[9]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~64~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[9] hbc_dq_IN_HI[9]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~66~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[9] hbc_dq_OUT_HI[9]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~66~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[9] hbc_dq_OUT_HI[9]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~66~322}] -max 0.263 [get_ports {hbc_dq_OE[9]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~66~322}] -min -0.140 [get_ports {hbc_dq_OE[9]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~57~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[10] hbc_dq_IN_HI[10]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~57~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[10] hbc_dq_IN_HI[10]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~59~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[10] hbc_dq_OUT_HI[10]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~59~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[10] hbc_dq_OUT_HI[10]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~59~322}] -max 0.263 [get_ports {hbc_dq_OE[10]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~59~322}] -min -0.140 [get_ports {hbc_dq_OE[10]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~56~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[11] hbc_dq_IN_HI[11]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~56~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[11] hbc_dq_IN_HI[11]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~58~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[11] hbc_dq_OUT_HI[11]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~58~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[11] hbc_dq_OUT_HI[11]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~58~322}] -max 0.263 [get_ports {hbc_dq_OE[11]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~58~322}] -min -0.140 [get_ports {hbc_dq_OE[11]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~49~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[12] hbc_dq_IN_HI[12]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~49~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[12] hbc_dq_IN_HI[12]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~51~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[12] hbc_dq_OUT_HI[12]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~51~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[12] hbc_dq_OUT_HI[12]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~51~322}] -max 0.263 [get_ports {hbc_dq_OE[12]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~51~322}] -min -0.140 [get_ports {hbc_dq_OE[12]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~48~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[13] hbc_dq_IN_HI[13]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~48~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[13] hbc_dq_IN_HI[13]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~50~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[13] hbc_dq_OUT_HI[13]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~50~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[13] hbc_dq_OUT_HI[13]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~50~322}] -max 0.263 [get_ports {hbc_dq_OE[13]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~50~322}] -min -0.140 [get_ports {hbc_dq_OE[13]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~25~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[14] hbc_dq_IN_HI[14]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~25~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[14] hbc_dq_IN_HI[14]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~27~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[14] hbc_dq_OUT_HI[14]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~27~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[14] hbc_dq_OUT_HI[14]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~27~322}] -max 0.263 [get_ports {hbc_dq_OE[14]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~27~322}] -min -0.140 [get_ports {hbc_dq_OE[14]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~24~322}] -max 0.414 [get_ports {hbc_dq_IN_LO[15] hbc_dq_IN_HI[15]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~24~322}] -min 0.276 [get_ports {hbc_dq_IN_LO[15] hbc_dq_IN_HI[15]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~26~322}] -max 0.263 [get_ports {hbc_dq_OUT_LO[15] hbc_dq_OUT_HI[15]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~26~322}] -min -0.140 [get_ports {hbc_dq_OUT_LO[15] hbc_dq_OUT_HI[15]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~26~322}] -max 0.263 [get_ports {hbc_dq_OE[15]}]
set_output_delay -clock_fall -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~26~322}] -min -0.140 [get_ports {hbc_dq_OE[15]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~129~322}] -max 0.414 [get_ports {hbc_rwds_IN_LO[0] hbc_rwds_IN_HI[0]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~129~322}] -min 0.276 [get_ports {hbc_rwds_IN_LO[0] hbc_rwds_IN_HI[0]}]
set_output_delay -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~131~322}] -max 0.263 [get_ports {hbc_rwds_OUT_LO[0] hbc_rwds_OUT_HI[0]}]
set_output_delay -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~131~322}] -min -0.140 [get_ports {hbc_rwds_OUT_LO[0] hbc_rwds_OUT_HI[0]}]
set_output_delay -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~131~322}] -max 0.263 [get_ports {hbc_rwds_OE[0]}]
set_output_delay -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~131~322}] -min -0.140 [get_ports {hbc_rwds_OE[0]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~72~322}] -max 0.414 [get_ports {hbc_rwds_IN_LO[1] hbc_rwds_IN_HI[1]}]
set_input_delay -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~72~322}] -min 0.276 [get_ports {hbc_rwds_IN_LO[1] hbc_rwds_IN_HI[1]}]
set_output_delay -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~74~322}] -max 0.263 [get_ports {hbc_rwds_OUT_LO[1] hbc_rwds_OUT_HI[1]}]
set_output_delay -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~74~322}] -min -0.140 [get_ports {hbc_rwds_OUT_LO[1] hbc_rwds_OUT_HI[1]}]
set_output_delay -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~74~322}] -max 0.263 [get_ports {hbc_rwds_OE[1]}]
set_output_delay -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~74~322}] -min -0.140 [get_ports {hbc_rwds_OE[1]}]

# Clockout Interface
######################
# CK_N -clock hbramClk90 -reference_pin [get_ports {hbramClk90~CLKOUT~83~322}]
# CK_P -clock hbramClk90 -reference_pin [get_ports {hbramClk90~CLKOUT~75~322}]
# CS_N -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~122~322}]
# DQ[0] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~167~322}]
# DQ[0] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~165~322}]
# DQ[10] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~59~322}]
# DQ[10] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~57~322}]
# DQ[11] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~58~322}]
# DQ[11] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~56~322}]
# DQ[12] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~51~322}]
# DQ[12] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~49~322}]
# DQ[13] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~50~322}]
# DQ[13] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~48~322}]
# DQ[14] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~27~322}]
# DQ[14] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~25~322}]
# DQ[15] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~26~322}]
# DQ[15] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~24~322}]
# DQ[1] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~166~322}]
# DQ[1] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~164~322}]
# DQ[2] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~159~322}]
# DQ[2] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~157~322}]
# DQ[3] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~158~322}]
# DQ[3] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~156~322}]
# DQ[4] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~151~322}]
# DQ[4] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~149~322}]
# DQ[5] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~150~322}]
# DQ[5] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~148~322}]
# DQ[6] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~143~322}]
# DQ[6] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~141~322}]
# DQ[7] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~142~322}]
# DQ[7] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~140~322}]
# DQ[8] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~67~322}]
# DQ[8] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~65~322}]
# DQ[9] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~66~322}]
# DQ[9] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~64~322}]
# RWDS[0] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~131~322}]
# RWDS[0] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~129~322}]
# RWDS[1] -clock hbramClk -reference_pin [get_ports {hbramClk~CLKOUT~74~322}]
# RWDS[1] -clock hbramClk_cal -reference_pin [get_ports {hbramClk_cal~CLKOUT~72~322}]
