#!/usr/bin/env bash
# Run Efinity flows for fpga-antic on the remote 'ubuntu' Linux box.
#
# Usage: ./run.sh [flow]   flow ∈ {map, pnr, pgm, full}   (default: map)
#
# Default target: Ti60F256 / Titanium / C4 — closes ram_clk @ 200 MHz
# with ~915 ps slack (244.8 MHz max). ~$38 at Q1, +$3 vs Tz50F256-I3
# but ~15× the ram_clk margin and +10K extra LUTs for the planned M23
# (POKEY) / M24 (SALLY) chip-absorption work. Pin-compatible with
# Tz50F256 in the F256 package — PCB drop-in.
#
# Override via env vars:
#   FAMILY=Topaz    DEVICE=Tz50F256 TIMING=I3 ./run.sh pnr   (Topaz I3 — $35, 61 ps slack at 200 MHz, narrow)
#   FAMILY=Topaz    DEVICE=Tz50F256 TIMING=C2 ./run.sh pnr   (consumer C2 — $26, 195.9 MHz, misses 200 MHz)
#   FAMILY=Trion    DEVICE=T20F256  TIMING=C4 ./run.sh pnr   (legacy small Trion — historic baseline)
# Each part change rebuilds clean (outflow/ + work_*/ are wiped before
# efx_run so a stale .vdb from another part can't masquerade as new).

set -euo pipefail

FLOW="${1:-map}"
# Each flow depends on the prior. After a clean of outflow/ + work_*/
# we always need to chain. `full` is reserved by efx_run for an
# include-rtlsim flow we don't want (no vendor sim license); use
# `pgm` for the map → pnr → bitstream chain.
case "$FLOW" in
    pnr) FLOWS="map pnr" ;;
    pgm) FLOWS="map pnr pgm" ;;
    *)   FLOWS="$FLOW" ;;
esac
REMOTE="ubuntu"
REMOTE_DIR="fpga-antic-build"
FAMILY="${FAMILY:-Titanium}"
DEVICE="${DEVICE:-Ti60F256}"
TIMING="${TIMING:-C4}"     # Ti60-C4 — ram_clk @ 244 MHz / +915 ps slack vs 200 target
TOP="${TOP:-antic_top}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_BUILD="$REPO_ROOT/efinity/build"

mkdir -p "$LOCAL_BUILD"

echo ">> syncing hdl/ -> $REMOTE:$REMOTE_DIR/hdl/"
ssh "$REMOTE" "mkdir -p $REMOTE_DIR"
rsync -az --delete "$REPO_ROOT/hdl/" "$REMOTE:$REMOTE_DIR/hdl/"

# IP files generated by efx_ipmgr (HyperRAM + future IPs). Each subdir
# under efinity/ip/ contains a top-level <name>.sv that we feed into
# synth alongside hdl/*.sv. Exclude reference designs (Ti60F* per-board
# variants), Testbench, IP-wizard's own outflow/, and the IP package
# manager (ipm/) — all unnecessary for our synth.
if [ -d "$REPO_ROOT/efinity/ip" ]; then
    rsync -az --delete \
        --exclude='Testbench' --exclude='Ti60F*' \
        --exclude='outflow' --exclude='ipm' \
        --exclude='*_tmpl.*' \
        "$REPO_ROOT/efinity/ip/" "$REMOTE:$REMOTE_DIR/ip/"
fi

# SDC is optional; sync if present
if [ -d "$REPO_ROOT/efinity/constraints" ]; then
    rsync -az --delete "$REPO_ROOT/efinity/constraints/" "$REMOTE:$REMOTE_DIR/constraints/"
fi

echo ">> running efx_run -f $FLOW (family=$FAMILY device=$DEVICE timing=$TIMING top=$TOP)"
# `--map_opts root=$TOP` tells efx_map (Efinix's Synplify wrapper) to
# treat $TOP as the root of the elaboration tree. Without it, Synplify
# picks an alphabetically-first leaf module (usually `vbeam`) and
# silently drops the rest of the design — yielding a misleadingly small
# / fast result. `root=NAME` is boost::program_options syntax (no
# leading dashes); efx_run's argparse strips dashes before pass-through.
#
# `efx_run` is incremental — it caches synth output from previous runs.
# If the file list or top-level changes, run.sh removes outflow/ and
# work_*/ on the remote first to force a clean build.
ssh "$REMOTE" bash -l <<EOF
set -eo pipefail
set +u
source ~/efinity/2025.2/bin/setup.sh
set -u
cd ~/$REMOTE_DIR
rm -rf outflow work_syn work_pnr work_pgm

# SDC location — the constraints/ rsync above puts it at
# constraints/<top>.sdc on the remote. PnR consumes it via
# --pnr_opts sdc_file=...
SDC_FILE=constraints/$TOP.sdc

# PnR effort knobs:
#   beneficial_skew=on   — Titanium-family clock-skew optimisation. Helps
#                          deep pipelines like the HyperRAM IP, but can
#                          slightly hurt other clock domains; toggleable
#                          via PNR_SKEW=off (default on).
#   physical_packing=on  — DSP/cluster packing based on placement; better
#                          QoR at small compile-time cost. PNR_PACK=off
#                          to disable.
#   max_router_iterations=200 — let the router grind (default ~50).
PNR_SKEW="\${PNR_SKEW:-on}"
PNR_PACK="\${PNR_PACK:-on}"
PNR_OPTS="beneficial_skew=\$PNR_SKEW physical_packing=\$PNR_PACK max_router_iterations=200"
if [ -f "\$SDC_FILE" ]; then
    PNR_OPTS="\$PNR_OPTS sdc_file=\$SDC_FILE"
fi

for f in $FLOWS; do
    # File list:
    #   - all hdl/**/*.sv except *_mock.sv (sim-only files)
    #   - all hdl/**/*.v   (vendor cores in hdl/sally/ etc. — none of
    #                       these are sim-only today)
    #   - all ip/*/*.sv except *_tmpl.sv (Efinity IP wizard templates)
    HDL_SV=\$(find hdl -name '*.sv' -not -name '*_mock.sv' | sort)
    HDL_V=\$(find hdl -name '*.v' | sort)
    # IP: top level only — subdirs hold vendor testbenches and per-board variants
    IP_SV=\$(ls ip/*/*.sv 2>/dev/null | grep -v '_tmpl\.sv$' || true)

    efx_run $TOP \
        -f \$f \
        --family $FAMILY \
        -d $DEVICE \
        --timing_model $TIMING \
        --dir hdl \
        -v \$HDL_SV \$HDL_V \$IP_SV \
        --map_opts root=$TOP \
        --pnr_opts \$PNR_OPTS
done
EOF

echo ">> syncing build artefacts back -> $LOCAL_BUILD/"
rsync -az "$REMOTE:$REMOTE_DIR/outflow/" "$LOCAL_BUILD/outflow/" 2>/dev/null || true
rsync -az "$REMOTE:$REMOTE_DIR/work_syn/" "$LOCAL_BUILD/work_syn/" 2>/dev/null || true
rsync -az "$REMOTE:$REMOTE_DIR/work_pnr/" "$LOCAL_BUILD/work_pnr/" 2>/dev/null || true
rsync -az "$REMOTE:$REMOTE_DIR/work_pgm/" "$LOCAL_BUILD/work_pgm/" 2>/dev/null || true

echo ">> done. artefacts in $LOCAL_BUILD/"
