#!/bin/sh
# build-dropbear.sh — compile the Dropbear SSH server (third_party/dropbear submodule,
# MIT) into objects for the XTOS dropbear.so. Out-of-tree so the submodule stays a
# pristine upstream checkout: config + stubs live in loader/dropbear-config/, config.h and
# the generated guard header land in loader/build/dropbear/, objects in build/dropbear/obj.
# The loader Makefile links the objects + libtomcrypt/libtommath archives + the shim into
# a PIC .so against libc.so (like toybox.so).
#
# The *.list files are written to a .tmp and RENAMED at the end of each loop. They are
# make targets, so a list left behind by a compile that died half-way is newer than every
# dependency and make treats it as complete — dropbear.so then links from the handful of
# objects that got as far as being listed, with no error anywhere. It links, it is a third
# the size, and it has no main. Failing must leave the OLD list, not a shorter new one.
#
# usage: tools/build-dropbear.sh   (from loader/)
set -e

LOADER=$(cd "$(dirname "$0")/.." && pwd)
DB=$(cd "$LOADER/../third_party/dropbear" && pwd)
# Honour the Makefile's BUILD (make BUILD=build-<who>): a private build dir is how two agents
# build this tree at once without racing each other's artefacts. Defaults to build/.
BUILD="$LOADER/${BUILDDIR:-build}/dropbear"
OBJ="$BUILD/obj"
mkdir -p "$OBJ"

if [ ! -f "$DB/configure" ]; then
    echo "dropbear submodule not initialised: run 'git submodule update --init third_party/dropbear'" >&2
    exit 1
fi

CROSS=arm-none-eabi-
CC=${CROSS}gcc
AR=${CROSS}ar
# NOTE: -DLTC_SOURCE is libtomcrypt-INTERNAL (only its own sources want it). Compiling
# Dropbear's files with it clashes libtomcrypt's math macros against libtommath's decls.
CFLAGS="-marm -mcpu=cortex-a9 -mfloat-abi=softfp -mfpu=neon-vfpv3 -fpic -fno-builtin \
 -DLOCALOPTIONS_H_EXISTS -DDROPBEAR_SERVER=1 -DDROPBEAR_CLIENT=0 -Os"
INC="-I$BUILD -I$LOADER/dropbear-config -I$DB/src -I$DB/libtomcrypt/src/headers \
 -I$DB/libtommath -I$LOADER/libc-compat -I$LOADER/newlib-pic/include"

# ---- config.h (autoconf; nosys.specs so cross link-tests pass) + guard header ----------
if [ ! -f "$BUILD/config.h" ]; then
    echo "[dropbear] configure..."
    ( cd "$BUILD" && env CC="$CC" \
        CFLAGS="-marm -mcpu=cortex-a9 -mfloat-abi=softfp -mfpu=neon-vfpv3 -fno-builtin \
                --specs=nosys.specs -I$LOADER/libc-compat -I$LOADER/newlib-pic/include" \
        "$DB/configure" --host=arm-none-eabi --disable-zlib --disable-pam --disable-syslog \
        --disable-lastlog --disable-utmp --disable-utmpx --disable-wtmp --disable-loginfunc \
        >/dev/null )
fi
# XTOS has no fork() (only vfork). configure's link test sees newlib's nosys fork stub and
# defines HAVE_FORK, which makes Dropbear use fork() (fails at runtime). Strip it so
# sysoptions.h selects DROPBEAR_VFORK=1 -> spawn_command uses vfork (which XTOS supports).
if grep -q '^#define HAVE_FORK 1' "$BUILD/config.h" 2>/dev/null; then
    grep -vx '#define HAVE_FORK 1' "$BUILD/config.h" > "$BUILD/config.h.tmp"
    mv "$BUILD/config.h.tmp" "$BUILD/config.h"
fi
# The mirror image: getrandom() DOES exist here (posix_shim.c, over SYS_getrandom),
# but configure's link test links against newlib alone and cannot see it, so it
# leaves HAVE_GETRANDOM undefined and dbrandom.c falls back to opening
# /dev/urandom. Same pool either way — but the syscall is the interface with the
# blocking guarantee, so take it.
if ! grep -q '^#define HAVE_GETRANDOM 1' "$BUILD/config.h" 2>/dev/null; then
    printf '\n#define HAVE_GETRANDOM 1\n' >> "$BUILD/config.h"
fi

printf '/* generated by build-dropbear.sh (do not edit) */\n\n' > "$BUILD/default_options_guard.h"
sh "$DB/src/ifndef_wrapper.sh" < "$DB/src/default_options.h" >> "$BUILD/default_options_guard.h"

# ---- server object set (from Makefile.in: COMMONOBJS + CLISVROBJS + SVROBJS + svr-main) --
COMMON="dbutil buffer dbhelpers dss bignum signkey rsa dbrandom queue atomicio compat \
 fake-rfc2553 ltc_prng ecc ecdsa sk-ecdsa crypto_desc curve25519 ed25519 sk-ed25519 \
 dbmalloc gensignkey gendss genrsa gened25519"
CLISVR="common-session packet common-algo common-kex common-channel common-chansession \
 termcodes loginrec tcp-accept listener process-packet dh_groups common-runopts circbuffer \
 list netio chachapoly gcm kex-x25519 kex-dh kex-ecdh kex-pqhybrid sntrup761 mlkem768"
SVR="svr-kex svr-auth sshpty svr-authpasswd svr-authpubkey svr-authpubkeyoptions svr-session \
 svr-service svr-chansession svr-runopts svr-agentfwd svr-main svr-x11fwd svr-tcpfwd svr-authpam"
# host-key generator, built into the same .so as the 'dropbearkey' applet
KEYGEN="dropbearkey"

# XTOS pty half-close: a pty master is ONE bidirectional fd, like the BSD-style
# ptys Dropbear's sshpty.c fallback scans. Upstream e28ba1b set ptycommand's
# bidir_fd=0 ("don't shutdown() a pty"), so a client half-close (CHANNEL_EOF —
# e.g. `ssh -tt host cmd < /dev/null`) close()es the master outright and any
# not-yet-drained shell output is lost. Our shutdown() is a no-op, so the
# pre-e28ba1b behaviour is the correct one here: EOF only marks the write side;
# the master really closes once both directions are done. Patched out-of-tree —
# the submodule stays pristine.
sed '/ses.maxfd = MAX(ses.maxfd, chansess->master);/{n;s/channel->bidir_fd = 0;/channel->bidir_fd = 1;/;}' \
    "$DB/src/svr-chansession.c" > "$BUILD/svr-chansession-xtos.c"
grep -q 'channel->bidir_fd = 1;' "$BUILD/svr-chansession-xtos.c" || {
    echo "build-dropbear.sh: bidir_fd patch no longer applies to svr-chansession.c" >&2; exit 1; }

echo "[dropbear] compiling server objects..."
: > "$BUILD/objects.list.tmp"
for f in $COMMON $CLISVR $SVR $KEYGEN; do
    o="$OBJ/$f.o"
    src="$DB/src/$f.c"
    [ "$f" = svr-chansession ] && src="$BUILD/svr-chansession-xtos.c"
    $CC $CFLAGS $INC -c "$src" -o "$o"
    echo "$o" >> "$BUILD/objects.list.tmp"
done
mv "$BUILD/objects.list.tmp" "$BUILD/objects.list"

# dropbearkey applet: the COMMON set + dropbearkey, compiled NEUTRAL (no DROPBEAR_SERVER
# -- it is neither server nor client). Its own object dir + list so the .so links cleanly.
echo "[dropbear] compiling dropbearkey (neutral) objects..."
KOBJ="$OBJ/key"; mkdir -p "$KOBJ"
KCFLAGS="-marm -mcpu=cortex-a9 -mfloat-abi=softfp -mfpu=neon-vfpv3 -fpic -fno-builtin \
 -DLOCALOPTIONS_H_EXISTS -Os"
: > "$BUILD/keyobjects.list.tmp"
for f in $COMMON $KEYGEN; do
    o="$KOBJ/$f.o"
    $CC $KCFLAGS $INC -c "$DB/src/$f.c" -o "$o"
    echo "$o" >> "$BUILD/keyobjects.list.tmp"
done
mv "$BUILD/keyobjects.list.tmp" "$BUILD/keyobjects.list"

# dbclient (/bin/ssh): COMMON + CLISVR + CLI compiled as CLIENT (its own object dir —
# the server set above is compiled -DDROPBEAR_SERVER=1/-DDROPBEAR_CLIENT=0 and the two
# can't share objects).
CLI="cli-main cli-auth cli-authpasswd cli-kex cli-session cli-runopts cli-chansession \
 cli-authpubkey cli-tcpfwd cli-channel cli-authinteract cli-agentfwd cli-readconf"
echo "[dropbear] compiling client (dbclient) objects..."
COBJ="$OBJ/cli"; mkdir -p "$COBJ"
CCFLAGS="-marm -mcpu=cortex-a9 -mfloat-abi=softfp -mfpu=neon-vfpv3 -fpic -fno-builtin \
 -DLOCALOPTIONS_H_EXISTS -DDROPBEAR_SERVER=0 -DDROPBEAR_CLIENT=1 -Os"
: > "$BUILD/cliobjects.list.tmp"
for f in $COMMON $CLISVR $CLI; do
    o="$COBJ/$f.o"
    $CC $CCFLAGS $INC -c "$DB/src/$f.c" -o "$o"
    echo "$o" >> "$BUILD/cliobjects.list.tmp"
done
mv "$BUILD/cliobjects.list.tmp" "$BUILD/cliobjects.list"

# scp (/bin/scp): standalone, neutral. Client mode (`scp file host:path` on XTOS)
# vfork+execs /bin/ssh (do_cmd's DROPBEAR_VFORK path = the shim's fake-vfork pattern);
# server mode (`scp -t/-f`, run by sshd-session for pushes/pulls) is pure stdio + fs.
SCP="scp progressmeter atomicio scpmisc compat"
echo "[dropbear] compiling scp objects..."
SOBJ="$OBJ/scp"; mkdir -p "$SOBJ"
: > "$BUILD/scpobjects.list.tmp"
for f in $SCP; do
    o="$SOBJ/$f.o"
    $CC $KCFLAGS $INC -c "$DB/src/$f.c" -o "$o"
    echo "$o" >> "$BUILD/scpobjects.list.tmp"
done
mv "$BUILD/scpobjects.list.tmp" "$BUILD/scpobjects.list"

# ---- crypto archives: libtomcrypt + libtommath (linker pulls only referenced members) ---
build_archive() {   # $1 = src dir, $2 = archive name, $3 = obj prefix, $4 = extra CFLAGS
    a="$BUILD/$2"
    [ -f "$a" ] && return 0
    echo "[dropbear] building $2 (this is the slow part, once)..."
    ao=""
    for src in $(find "$1" -name '*.c'); do
        b=$3_$(echo "$src" | sed "s|$1/||; s|/|_|g; s|\.c$||")
        if $CC $CFLAGS $4 $INC -c "$src" -o "$OBJ/$b.o" 2>/dev/null; then
            ao="$ao $OBJ/$b.o"
        fi
    done
    $AR rcs "$a" $ao
}
build_archive "$DB/libtomcrypt/src" libtomcrypt.a ltc -DLTC_SOURCE
build_archive "$DB/libtommath" libtommath.a ltm ""

echo "[dropbear] objects ready: $(wc -l < "$BUILD/objects.list" | tr -d ' ') server objs + libtomcrypt.a + libtommath.a"
