#!/bin/sh
# Emit the newlib-pic provenance stamp for the CURRENT artifacts to stdout.
#
# The stamp pins the exact validated libc.a/libm.a (and the recipe that built
# them) so we can answer one question: "is the newlib-pic I'm linking against
# the one that was patched/validated, or a random local rebuild?"
#
# Two consumers, one format:
#   - tools/build-newlib-pic.sh  writes newlib-pic/STAMP after a build.
#   - `make newlib-check`        diffs this against the checked-in golden
#                                 loader/newlib-pic.stamp.
#
# Deliberately contains NO volatile fields (build date, host, paths): the body
# is a pure function of (recipe, artifacts) so a match is meaningful. Provenance
# of *when* it was validated lives in the golden file's git history.
set -e
SELF=$(cd "$(dirname "$0")" && pwd)          # loader/tools
NP=$(cd "$SELF/.." && pwd)/newlib-pic         # loader/newlib-pic
BUILD=$SELF/build-newlib-pic.sh

[ -f "$NP/libc.a" ] && [ -f "$NP/libm.a" ] || {
  echo "newlib-stamp: newlib-pic/{libc.a,libm.a} not found — run tools/build-newlib-pic.sh" >&2
  exit 2
}

sha256() {   # macOS ships shasum; Linux ships sha256sum. Prefer the latter.
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
  else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

# Version comes from the BUILT artifact (its _newlib_version.h), not the build
# script — so the line reports what was actually compiled and can't drift from a
# VER override passed at build time. The exact release/snapshot (e.g. the
# .20231231 tail that the header's "4.4.0" drops) is pinned precisely by
# libc_a_sha256 below. multilib is a plain line in the recipe; config_sha256 is
# the recipe itself (build flags), so a flags change flips the stamp too.
VER=$(sed -n 's/.*_NEWLIB_VERSION "\([^"]*\)".*/\1/p'   "$NP/include/_newlib_version.h" | head -1)
ML=$(sed  -n 's/^ML=\([^[:space:]]*\).*/\1/p'           "$BUILD" | head -1)

cat <<EOF
# newlib-pic provenance stamp — generated by tools/newlib-stamp.sh; do not edit.
# A checked-in copy of this at loader/newlib-pic.stamp is the VALIDATED record.
# newlib_version is from the built _newlib_version.h; the exact release/snapshot
# is pinned by libc_a_sha256 (the header only carries the X.Y.Z triple).
newlib_version $VER
multilib       $ML
config_sha256  $(sha256 "$BUILD")
libc_a_sha256  $(sha256 "$NP/libc.a")
libm_a_sha256  $(sha256 "$NP/libm.a")
EOF
