#!/usr/bin/env bash
# build_boot_bin.sh — package FSBL + bitstream + app ELF into BOOT.BIN.
#
# Mac-side wrapper: generates a BIF, pushes it to win10, runs bootgen
# there (it lives in the Vitis install), and scp's the resulting
# BOOT.BIN back.  Output is gitignored.
#
# Usage:
#   ./build_boot_bin.sh                          # default paths
#   ./build_boot_bin.sh <local_out_path>         # custom output location
#
# Prerequisites:
#   1. vivado/build/fpga_xt_top.bit on win10  (vivado/run-win10.sh bit)
#   2. vitis/workspace/fsbl/build/fsbl.elf and
#      vitis/workspace/app_blink/build/app_blink.elf on win10
#      (Vitis -s scripts/create_platform.py — see vitis/README.md)
#
# Env-var overrides:
#   REMOTE       win10                                       (SSH alias)
#   REMOTE_DIR   C:/Users/simon/fpga                         (work tree)
#   BOOTGEN      C:\Xilinx\2025.2.1\Vitis\bin\bootgen.bat    (tool path)
#   FSBL, BIT, APP   absolute remote paths to override the canonical
#                    artefact locations under REMOTE_DIR.

set -euo pipefail

REMOTE="${REMOTE:-win10}"
REMOTE_DIR="${REMOTE_DIR:-C:/Users/simon/fpga}"
BOOTGEN="${BOOTGEN:-C:\\Xilinx\\2025.2.1\\Vitis\\bin\\bootgen.bat}"

FSBL="${FSBL:-$REMOTE_DIR/vitis/workspace/fsbl/build/fsbl.elf}"
BIT="${BIT:-$REMOTE_DIR/build/fpga_xt_top.bit}"
APP="${APP:-$REMOTE_DIR/vitis/workspace/app_blink/build/app_blink.elf}"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
LOCAL_OUT="${1:-$REPO_ROOT/vitis/BOOT.BIN}"

# Sanity-check the remote artefacts before generating anything.
echo ">> checking remote artefacts ..."
for path in "$FSBL" "$BIT" "$APP"; do
    if ! ssh "$REMOTE" "Test-Path '$path'" | grep -q True; then
        echo "ERROR: missing on $REMOTE: $path" >&2
        exit 1
    fi
done

# Compose the BIF locally — easier than fighting PowerShell heredocs
# through SSH.  Paths inside the BIF are the remote absolute paths
# that bootgen will resolve on win10.
TMP_BIF=$(mktemp -t boot.bif.XXXXXX)
trap "rm -f $TMP_BIF" EXIT
cat > "$TMP_BIF" <<EOF
// Generated by vitis/scripts/build_boot_bin.sh — do not edit.
the_ROM_image:
{
    [bootloader] $FSBL
    $BIT
    $APP
}
EOF

REMOTE_BIF="$REMOTE_DIR/boot.bif"
REMOTE_OUT="$REMOTE_DIR/BOOT.BIN"

scp -q "$TMP_BIF" "$REMOTE:$REMOTE_BIF"

echo ">> running bootgen on $REMOTE ..."
ssh "$REMOTE" "& '$BOOTGEN' -arch zynq -image '$REMOTE_BIF' -o '$REMOTE_OUT' -w on"

echo ">> pulling BOOT.BIN -> $LOCAL_OUT"
mkdir -p "$(dirname "$LOCAL_OUT")"
scp -q "$REMOTE:$REMOTE_OUT" "$LOCAL_OUT"
ls -lh "$LOCAL_OUT"
