/* xt_gp0_map.h — GENERATED by tools/gen_regmap.py from hdl/regmap/xt_gp0.json — DO NOT EDIT.
 *
 * The PL control-register map over PS GP0 (@ 0x43C00000).
 * Single source of truth: hdl/regmap/xt_gp0.json (mirrors the hardware
 * decode in hdl/xt_gp0_regs.sv via the generated hdl/xt_gp0_pkg.sv).
 *
 *   The slave claims 0x000..0xFFF (addr[15:12]==0); sally_rom_loader OR-muxes at 0x1000+.
 *   Every register is 32-bit word-aligned (Xil_In32/Out32, no byte-lane tricks); reads never alias writes.
 *   Runs on clk_sys (same domain as the blitter) — no CDC on the register bus.
 *
 *   0x000  BLITTER     blit regs (offset = bl_addr) + STATUS/SEQ reads; dual-access 6502 $D4Bx/$D4Cx/$D4Ex under UNLK_BLIT
 *   0x100  SPRITE      sprite-engine reg index/data port; dual-access 6502 $D4Ax/$D4Dx under UNLK_SPRITE
 *   0x200  COMP        drag-overlay config (A9-only, whole 32-bit words)
 *   0x300  CTRL        control plane (gp0_ctrl, SALLY speed, XT unlock, keyboard inject)
 *   0x400  DIAG        PL diagnostic words (A9-only, read-only, word-aligned)
 *   0x500  XLCTL       XL compositor-plane window placement (A9-positioned emulation window)
 */
#ifndef XT_GP0_MAP_H_
#define XT_GP0_MAP_H_

#ifndef XT_GP0_BASE
#define XT_GP0_BASE      0x43C00000u
#endif

/* ---- per-device block bases --------------------------------------------- */
#define XT_BLK_BLITTER   (XT_GP0_BASE + 0x000u)
#define XT_BLK_SPRITE    (XT_GP0_BASE + 0x100u)
#define XT_BLK_COMP      (XT_GP0_BASE + 0x200u)
#define XT_BLK_CTRL      (XT_GP0_BASE + 0x300u)
#define XT_BLK_DIAG      (XT_GP0_BASE + 0x400u)
#define XT_BLK_XLCTL     (XT_GP0_BASE + 0x500u)

/* ---- BLITTER block --------------------------------------------------- */
/*   0x00..0x18  W  blitter registers DST/PAT/CMD/SRC/FLAGS (bl_addr = offset); see blitter.h XT_BL_* */
/*   0x30..0x3B  W  SRC/DST DDR-surface descriptors / ROW0 bases (bl_addr = offset) */
#define XT_BLT_STATUS        (XT_BLK_BLITTER + 0x40u)     /* R {pat_blocked[2], queue_full[1], busy[0]} */
#define XT_BLT_SEQ           (XT_BLK_BLITTER + 0x44u)     /* R seq_counter[15:0] */

/* ---- SPRITE block --------------------------------------------------- */
#define XT_SPR_IDX           (XT_BLK_SPRITE + 0x00u)      /* W latch sprite reg index */
#define XT_SPR_DATA          (XT_BLK_SPRITE + 0x04u)      /* W sprite reg data + strobe (writes idx/data to engine) */
#define XT_SPR_COLL          (XT_BLK_SPRITE + 0x08u)      /* R collision[col_sel] (set col_sel first via $D4D9); [15:0] = sprites this one hit */

/* ---- COMP block --------------------------------------------------- */
#define XT_OVL_EN            (XT_BLK_COMP + 0x00u)        /* W [0]=enable; also toggles the commit flag */
#define XT_OVL_BASE          (XT_BLK_COMP + 0x04u)        /* W DDR byte address (32-bit) */
#define XT_OVL_X             (XT_BLK_COMP + 0x08u)        /* W on-screen X (12-bit) */
#define XT_OVL_Y             (XT_BLK_COMP + 0x0Cu)        /* W on-screen Y (12-bit) */
#define XT_OVL_W             (XT_BLK_COMP + 0x10u)        /* W width px (12-bit; stride = w<<2) */
#define XT_OVL_H             (XT_BLK_COMP + 0x14u)        /* W height px (12-bit) */

/* ---- CTRL block --------------------------------------------------- */
#define XT_CTRL_GP0          (XT_BLK_CTRL + 0x00u)        /* RW [0]=bars, [3:1]=XL scale, [4]=DMACTL-blank (A9-only); read = effective */
#define XT_CTRL_SPEED        (XT_BLK_CTRL + 0x04u)        /* RW SALLY clock_mult (dual: 6502 $D4CA); read = effective. W -> bl_addr $D4CA */
#define XT_CTRL_UNLOCK       (XT_BLK_CTRL + 0x08u)        /* RW XT register-unlock (dual: 6502 $D1DF); read = effective */
#define XT_CTRL_KBD_INJECT   (XT_BLK_CTRL + 0x0Cu)        /* W KBCODE + POKEY IRQ (A9-only; emits $D4CF) */
#define XT_CTRL_KBD_RELEASE  (XT_BLK_CTRL + 0x10u)        /* W all-keys-up (A9-only; emits $D4CD) */
#define XT_CTRL_KBD_BREAK    (XT_BLK_CTRL + 0x14u)        /* W Atari BREAK (A9-only; emits $D4CB) */

/* ---- DIAG block --------------------------------------------------- */
#define XT_DIAG0             (XT_BLK_DIAG + 0x00u)        /* R MMCM locks / clk_pix-alive / frame count */
#define XT_DIAG2             (XT_BLK_DIAG + 0x04u)        /* R production-chain counters */
#define XT_DIAG3             (XT_BLK_DIAG + 0x08u)        /* R read-path activity */
#define XT_DIAG4             (XT_BLK_DIAG + 0x0Cu)        /* R HP3 (XL) first-AR address */
#define XT_DIAG5             (XT_BLK_DIAG + 0x10u)        /* R HP0 (desktop) first-AR address */
#define XT_DIAG6             (XT_BLK_DIAG + 0x14u)        /* R HP2 read-probe status */
#define XT_DIAG7             (XT_BLK_DIAG + 0x18u)        /* R HP2 read-probe last rdata */

/* ---- XLCTL block --------------------------------------------------- */
#define XT_XL_WIN_X          (XT_BLK_XLCTL + 0x00u)       /* W plane origin X on screen (12-bit) */
#define XT_XL_WIN_Y          (XT_BLK_XLCTL + 0x04u)       /* W plane origin Y on screen (12-bit) */
#define XT_XL_WIN_W          (XT_BLK_XLCTL + 0x08u)       /* W clip width  (12-bit; clip_x1 = X + W) */
#define XT_XL_WIN_H          (XT_BLK_XLCTL + 0x0Cu)       /* W clip height (12-bit; clip_y1 = Y + H) */
#define XT_XL_WIN_SCALE      (XT_BLK_XLCTL + 0x10u)       /* W integer scale 1..5 */
#define XT_XL_WIN_EN         (XT_BLK_XLCTL + 0x14u)       /* W [0]=1: use these regs (A9-positioned); 0: legacy gp0_ctrl-scale centred */

#endif /* XT_GP0_MAP_H_ */
