// xt_gp0_pkg.sv — GENERATED by tools/gen_regmap.py from hdl/regmap/xt_gp0.json — DO NOT EDIT.
//
// Block selectors (addr[11:8]) and per-block register offsets (addr[7:0])
// for the GP0 control-register file.  Imported by xt_gp0_regs.sv so the RTL
// decode and the A9-side xt_gp0_map.h cannot drift.
`ifndef XT_GP0_PKG_SV
`define XT_GP0_PKG_SV
package xt_gp0_pkg;

    // ---- block selectors = addr[11:8] ----
    localparam logic [3:0] BLK_BLITTER  = 4'h0;  // 0x000  BLITTER
    localparam logic [3:0] BLK_SPRITE   = 4'h1;  // 0x100  SPRITE
    localparam logic [3:0] BLK_COMP     = 4'h2;  // 0x200  COMP
    localparam logic [3:0] BLK_CTRL     = 4'h3;  // 0x300  CTRL
    localparam logic [3:0] BLK_DIAG     = 4'h4;  // 0x400  DIAG
    localparam logic [3:0] BLK_XLCTL    = 4'h5;  // 0x500  XLCTL
    localparam logic [3:0] BLK_MATH     = 4'h6;  // 0x600  MATH
    localparam logic [3:0] BLK_TRNG     = 4'h7;  // 0x700  TRNG

    // ---- register offsets = addr[7:0] (per block) ----
    // BLITTER
    localparam logic [7:0] BLT_REG_LO       = 8'h00;  // W blitter registers DST/PAT/CMD/SRC/FLAGS (bl_addr = offset); see blitter.h XT_BL_*
    localparam logic [7:0] BLT_REG_HI       = 8'h18;
    localparam logic [7:0] BLT_DESC_LO      = 8'h30;  // W SRC/DST DDR-surface descriptors / ROW0 bases (bl_addr = offset)
    localparam logic [7:0] BLT_DESC_HI      = 8'h3B;
    localparam logic [7:0] BLT_STATUS       = 8'h40;  // R {pat_blocked[2], queue_full[1], busy[0]}
    localparam logic [7:0] BLT_SEQ          = 8'h44;  // R seq_counter[15:0]
    // SPRITE
    localparam logic [7:0] SPR_IDX          = 8'h00;  // W latch sprite reg index
    localparam logic [7:0] SPR_DATA         = 8'h04;  // W sprite reg data + strobe (writes idx/data to engine)
    localparam logic [7:0] SPR_COLL         = 8'h08;  // R collision[col_sel] (set col_sel first via $D4D9); [15:0] = sprites this one hit
    // COMP
    localparam logic [7:0] OVL_EN           = 8'h00;  // W [0]=enable; also toggles the commit flag
    localparam logic [7:0] OVL_BASE         = 8'h04;  // W DDR byte address (32-bit)
    localparam logic [7:0] OVL_X            = 8'h08;  // W on-screen X (12-bit)
    localparam logic [7:0] OVL_Y            = 8'h0C;  // W on-screen Y (12-bit)
    localparam logic [7:0] OVL_W            = 8'h10;  // W width px (12-bit; stride = w<<2)
    localparam logic [7:0] OVL_H            = 8'h14;  // W height px (12-bit)
    // CTRL
    localparam logic [7:0] CTRL_GP0         = 8'h00;  // RW [0]=bars, [3:1]=XL scale, [4]=DMACTL-blank, [5]=video-sleep (gate clk_pix off) (A9-only); read = effective
    localparam logic [7:0] CTRL_SPEED       = 8'h04;  // RW SALLY clock_mult (dual: 6502 $D4CA); read = effective. W -> bl_addr $D4CA
    localparam logic [7:0] CTRL_UNLOCK      = 8'h08;  // RW XT register-unlock (dual: 6502 $D1DF); read = effective
    localparam logic [7:0] CTRL_KBD_INJECT  = 8'h0C;  // W KBCODE + POKEY IRQ (A9-only; emits $D4CF)
    localparam logic [7:0] CTRL_KBD_RELEASE = 8'h10;  // W all-keys-up (A9-only; emits $D4CD)
    localparam logic [7:0] CTRL_KBD_BREAK   = 8'h14;  // W Atari BREAK (A9-only; emits $D4CB)
    localparam logic [7:0] CTRL_CMPCFG      = 8'h18;  // RW compositor plane arrangement (A9-only; reset 0x210 = current). depth: [3:0]=desktop, [7:4]=overlay, [11:8]=XL. alpha_en: [16]=desktop, [17]=overlay, [18]=XL. Route-A flip = desktop on top with alpha (0x00010132)
    localparam logic [7:0] CTRL_SALLYRST    = 8'h1C;  // RW [0]=1 HOLD the SALLY realm in reset (A9-only; reset 0 = running). Cold-boot-per-launch: hold, rewrite the OS/RAM through the ROM-loader window (0x1000+), release = fresh coldstart. Resets the 6502 core AND the XT state a stock guest cannot know about (bank selects $D5C0/$D5C1, screen banking $D5C3-5); the video pipeline keeps scanning
    // DIAG
    localparam logic [7:0] DIAG0            = 8'h00;  // R MMCM locks / clk_pix-alive / frame count
    localparam logic [7:0] DIAG2            = 8'h04;  // R production-chain counters
    localparam logic [7:0] DIAG3            = 8'h08;  // R read-path activity
    localparam logic [7:0] DIAG4            = 8'h0C;  // R HP3 (XL) first-AR address
    localparam logic [7:0] DIAG5            = 8'h10;  // R HP0 (desktop) first-AR address
    localparam logic [7:0] DIAG6            = 8'h14;  // R HP2 read-probe status
    localparam logic [7:0] DIAG7            = 8'h18;  // R HP2 read-probe last rdata
    localparam logic [7:0] DIAG8            = 8'h1C;  // R TEMP ROM-window upload diag: [31:16]=window AXI writes accepted, [15:0]=rom_we pulses emitted to sally_mem
    localparam logic [7:0] DIAG9            = 8'h20;  // R TEMP ROM-window upload diag: [23:8]=last rom_addr, [7:0]=last rom_data
    // XLCTL
    localparam logic [7:0] XL_WIN_X         = 8'h00;  // W plane origin X on screen (12-bit)
    localparam logic [7:0] XL_WIN_Y         = 8'h04;  // W plane origin Y on screen (12-bit)
    localparam logic [7:0] XL_WIN_W         = 8'h08;  // W clip width  (12-bit; clip_x1 = X + W)
    localparam logic [7:0] XL_WIN_H         = 8'h0C;  // W clip height (12-bit; clip_y1 = Y + H)
    localparam logic [7:0] XL_WIN_SCALE     = 8'h10;  // W integer scale 1..5
    localparam logic [7:0] XL_WIN_EN        = 8'h14;  // W [0]=1: use these regs (A9-positioned); 0: legacy gp0_ctrl-scale centred
    // MATH
    localparam logic [7:0] MATH_EVT         = 8'h00;  // R doorbell event pop: [8]=valid, [7:0]=chunk index; a read consumes one event; IRQ_F2P[1] level = FIFO non-empty
    localparam logic [7:0] MATH_DONE        = 8'h04;  // W completion: [7:0]=chunk, [15:8]=result-span first line (64 B lines), [23:16]=line count; reloads the span into the math page if that chunk is resident, then raises $D5C7 done
    localparam logic [7:0] MATH_STAT        = 8'h08;  // R [0]=engine busy, [1]=chunk resident/ready, [2]=evt FIFO non-empty, [15:8]=resident chunk, [23:16]=evt FIFO fill
    // TRNG
    localparam logic [7:0] TRNG_RND         = 8'h00;  // R whitened 32-bit entropy word (free-running pool snapshot); read repeatedly for fresh words. Entropy SOURCE for the OS pool, not raw crypto output

endpackage
`endif
