// xt_gp0_pkg.sv — GENERATED by tools/gen_regmap.py from hdl/regmap/xt_gp0.json — DO NOT EDIT.
//
// Block selectors (addr[11:8]) and per-block register offsets (addr[7:0])
// for the GP0 control-register file.  Imported by xt_gp0_regs.sv so the RTL
// decode and the A9-side xt_gp0_map.h cannot drift.
`ifndef XT_GP0_PKG_SV
`define XT_GP0_PKG_SV
package xt_gp0_pkg;

    // ---- block selectors = addr[11:8] ----
    localparam logic [3:0] BLK_BLITTER  = 4'h0;  // 0x000  BLITTER
    localparam logic [3:0] BLK_SPRITE   = 4'h1;  // 0x100  SPRITE
    localparam logic [3:0] BLK_COMP     = 4'h2;  // 0x200  COMP
    localparam logic [3:0] BLK_CTRL     = 4'h3;  // 0x300  CTRL
    localparam logic [3:0] BLK_DIAG     = 4'h4;  // 0x400  DIAG
    localparam logic [3:0] BLK_XLCTL    = 4'h5;  // 0x500  XLCTL
    localparam logic [3:0] BLK_MATH     = 4'h6;  // 0x600  MATH
    localparam logic [3:0] BLK_TRNG     = 4'h7;  // 0x700  TRNG
    localparam logic [3:0] BLK_DEBUG    = 4'h8;  // 0x800  DEBUG

    // ---- register offsets = addr[7:0] (per block) ----
    // BLITTER
    localparam logic [7:0] BLT_REG_LO       = 8'h00;  // W blitter registers DST/PAT/CMD/SRC/FLAGS (bl_addr = offset); see blitter.h XT_BL_*
    localparam logic [7:0] BLT_REG_HI       = 8'h18;
    localparam logic [7:0] BLT_DESC_LO      = 8'h30;  // W SRC/DST DDR-surface descriptors / ROW0 bases (bl_addr = offset)
    localparam logic [7:0] BLT_DESC_HI      = 8'h3B;
    localparam logic [7:0] BLT_STATUS       = 8'h40;  // R {pat_blocked[2], queue_full[1], busy[0]}
    localparam logic [7:0] BLT_SEQ          = 8'h44;  // R seq_counter[15:0]
    // SPRITE
    localparam logic [7:0] SPR_IDX          = 8'h00;  // W latch sprite reg index
    localparam logic [7:0] SPR_DATA         = 8'h04;  // W sprite reg data + strobe (writes idx/data to engine)
    localparam logic [7:0] SPR_COLL         = 8'h08;  // R collision[col_sel] (set col_sel first via $D4D9); [15:0] = sprites this one hit
    // COMP
    localparam logic [7:0] OVL_EN           = 8'h00;  // W [0]=enable; also toggles the commit flag
    localparam logic [7:0] OVL_BASE         = 8'h04;  // W DDR byte address (32-bit)
    localparam logic [7:0] OVL_X            = 8'h08;  // W on-screen X (12-bit)
    localparam logic [7:0] OVL_Y            = 8'h0C;  // W on-screen Y (12-bit)
    localparam logic [7:0] OVL_W            = 8'h10;  // W width px (12-bit; stride = w<<2)
    localparam logic [7:0] OVL_H            = 8'h14;  // W height px (12-bit)
    // CTRL
    localparam logic [7:0] CTRL_GP0         = 8'h00;  // RW [0]=bars, [3:1]=XL scale, [4]=DMACTL-blank, [5]=video-sleep (gate clk_pix off) (A9-only); read = effective
    localparam logic [7:0] CTRL_SPEED       = 8'h04;  // RW SALLY clock_mult (dual: 6502 $D4CA); read = effective. W -> bl_addr $D4CA
    localparam logic [7:0] CTRL_UNLOCK      = 8'h08;  // RW XT register-unlock (dual: 6502 $D1DF); read = effective
    localparam logic [7:0] CTRL_KBD_INJECT  = 8'h0C;  // W KBCODE + POKEY IRQ (A9-only; emits $D4CF)
    localparam logic [7:0] CTRL_KBD_RELEASE = 8'h10;  // W all-keys-up (A9-only; emits $D4CD)
    localparam logic [7:0] CTRL_KBD_BREAK   = 8'h14;  // W Atari BREAK (A9-only; emits $D4CB)
    localparam logic [7:0] CTRL_CMPCFG      = 8'h18;  // RW compositor plane arrangement (A9-only; reset 0x210 = current). depth: [3:0]=desktop, [7:4]=overlay, [11:8]=XL. alpha_en: [16]=desktop, [17]=overlay, [18]=XL. Route-A flip = desktop on top with alpha (0x00010132)
    localparam logic [7:0] CTRL_SALLYRST    = 8'h1C;  // RW [0]=1 HOLD the SALLY realm in reset (A9-only; reset 0 = running). Cold-boot-per-launch: hold, rewrite the OS/RAM through the ROM-loader window (0x1000+), release = fresh coldstart. Resets the 6502 core AND the XT state a stock guest cannot know about (bank selects $D5C0/$D5C1, screen banking $D5C3-5); the video pipeline keeps scanning
    localparam logic [7:0] CTRL_JOY_OVR     = 8'h20;  // W keypad->joystick override (A9-only; forces STICK0/1 PORTA pins + TRIG0 when the physical PCAL9722 joystick is absent). [31]=override enable (0 = joy_bridge/PCAL9722 drives as normal). [7:0]=PORTA pin value, ACTIVE-LOW (STICK0 bits[3:0]: bit0=up bit1=down bit2=left bit3=right; STICK1 bits[7:4]; 1=released 0=pressed; 0xFF=neutral). [8]=TRIG0/fire value, ACTIVE-LOW (0=fire pressed). Muxed into pia_regs PORTA + GTIA TRIG0 in antic_top; the joy_bridge write-through path is untouched
    localparam logic [7:0] CTRL_CONSOL      = 8'h24;  // W console-keys value the 6502 reads as CONSOL ($D01F). ACTIVE-LOW: bit0=START bit1=SELECT bit2=OPTION (0=pressed). Reset $07 (none). The kernel holds OPTION ($03) across a game coldstart so the XL OS leaves BASIC DISABLED ($A000-$BFFF stays RAM) — no game boots with BASIC mapped, and BASIC shadowing RAM was crashing games; releases to $07 for boot-to-BASIC (READY). Replaces the hardwired 8'h07 in antic_top
    // DIAG
    localparam logic [7:0] DIAG0            = 8'h00;  // R MMCM locks / clk_pix-alive / frame count
    localparam logic [7:0] DIAG2            = 8'h04;  // R production-chain counters
    localparam logic [7:0] DIAG3            = 8'h08;  // R read-path activity
    localparam logic [7:0] DIAG4            = 8'h0C;  // R HP3 (XL) first-AR address
    localparam logic [7:0] DIAG5            = 8'h10;  // R HP0 (desktop) first-AR address
    localparam logic [7:0] DIAG6            = 8'h14;  // R HP2 read-probe status
    localparam logic [7:0] DIAG7            = 8'h18;  // R HP2 read-probe last rdata
    localparam logic [7:0] DIAG8            = 8'h1C;  // R TEMP ROM-window upload diag: [31:16]=window AXI writes accepted, [15:0]=rom_we pulses emitted to sally_mem
    localparam logic [7:0] DIAG9            = 8'h20;  // R TEMP ROM-window upload diag: [23:8]=last rom_addr, [7:0]=last rom_data
    localparam logic [7:0] DIAG10           = 8'h24;  // R TEMP compositor P/M FETCH capture (antic_pmdma $00 bug): [31:16]=last cmp_raddr in $2000-$3FFF, [15:8]=0, [7:0]=cmp_rdata byte returned
    localparam logic [7:0] DIAG11           = 8'h28;  // R TEMP compositor P/M-region fetch counter: increments each cmp_ready with cmp_raddr in $2000-$3FFF
    localparam logic [7:0] DIAG12           = 8'h2C;  // R TEMP nmi_gen DLI/VBI counters: [31:24]=dli_nmi_count (gated DLI /NMI assertions), [23:16]=vbi_nmi_count, [15:8]=dli_event_count (DLIs detected regardless of NMIEN), [7:0]=last NMIST (external view) sampled just after the last /NMI assertion
    localparam logic [7:0] DIAG13           = 8'h30;  // R TEMP nmi_gen NMI state: [31:24]=nmien, [23:16]=last-DLI antic_raster scanline[7:0], [15:0]=total DLI+VBI /NMI assertion count
    localparam logic [7:0] DIAG14           = 8'h34;  // R TEMP NMIEN sticky evidence (DLI cluster): [31:16]=CPU write count to $D40E, [15:8]=sticky-OR of every live ANTIC nmien_q value (bit15=nmien_or[7]: 1 -> bit7 EVER latched in nmien_q; 0 -> bit7 never reaches nmien_q), [7:1]=0, [0]=nmien_dli_coincide (sticky: nmien_q[7] high on a DLI line-start)
    localparam logic [7:0] DIAG15           = 8'h38;  // R TEMP player-0 P/M FETCH capture (antic_pmdma $00 bug): [31:16]=last cmp_raddr in $3400-$34FF (player-0 one-line region only) with a NON-ZERO returned byte, [15:8]=cmp_p0_nz_cnt (saturating count of non-zero P0 fetches; 0=no shape byte ever), [7:0]=cmp_rdata non-zero byte returned
    // XLCTL
    localparam logic [7:0] XL_WIN_X         = 8'h00;  // W plane origin X on screen (12-bit)
    localparam logic [7:0] XL_WIN_Y         = 8'h04;  // W plane origin Y on screen (12-bit)
    localparam logic [7:0] XL_WIN_W         = 8'h08;  // W clip width  (12-bit; clip_x1 = X + W)
    localparam logic [7:0] XL_WIN_H         = 8'h0C;  // W clip height (12-bit; clip_y1 = Y + H)
    localparam logic [7:0] XL_WIN_SCALE     = 8'h10;  // W integer scale 1..5
    localparam logic [7:0] XL_WIN_EN        = 8'h14;  // W [0]=1: use these regs (A9-positioned); 0: legacy gp0_ctrl-scale centred
    // MATH
    localparam logic [7:0] MATH_EVT         = 8'h00;  // R doorbell event pop: [8]=valid, [7:0]=chunk index; a read consumes one event; IRQ_F2P[1] level = FIFO non-empty
    localparam logic [7:0] MATH_DONE        = 8'h04;  // W completion: [7:0]=chunk, [15:8]=result-span first line (64 B lines), [23:16]=line count; reloads the span into the math page if that chunk is resident, then raises $D5C7 done
    localparam logic [7:0] MATH_STAT        = 8'h08;  // R [0]=engine busy, [1]=chunk resident/ready, [2]=evt FIFO non-empty, [15:8]=resident chunk, [23:16]=evt FIFO fill
    // TRNG
    localparam logic [7:0] TRNG_RND         = 8'h00;  // R whitened 32-bit entropy word (free-running pool snapshot); read repeatedly for fresh words. Entropy SOURCE for the OS pool, not raw crypto output
    // DEBUG
    localparam logic [7:0] DBG_HALT         = 8'h00;  // W write (any) -> run to the next instruction boundary, then freeze (state preserved). Also arms halt-at-reset when combined with a SALLYRST pulse
    localparam logic [7:0] DBG_GO           = 8'h04;  // W write (any) -> release the core, run at the configured speed
    localparam logic [7:0] DBG_STEP         = 8'h08;  // W write N -> execute exactly N instructions (min 1) then freeze
    localparam logic [7:0] DBG_CFG          = 8'h0C;  // RW [0]=bkpt_en (arm the PC breakpoint), [1]=halt_at_reset (freeze at the reset-vector fetch after the next SALLYRST release)
    localparam logic [7:0] DBG_BKPT         = 8'h10;  // RW [15:0]=breakpoint PC; when bkpt_en, the core freezes at the ST_FETCH of this address (before executing it)
    localparam logic [7:0] DBG_COMMIT       = 8'h14;  // W write (any) -> inject DBG_WPC/WAXYS/WPSH into the core's PC/regs and re-anchor at ST_FETCH (only meaningful while halted)
    localparam logic [7:0] DBG_WPC          = 8'h18;  // RW [15:0]=PC to inject on DBG_COMMIT
    localparam logic [7:0] DBG_WAXYS        = 8'h1C;  // RW regs to inject on DBG_COMMIT: [7:0]=A [15:8]=X [23:16]=Y [31:24]=SP(low)
    localparam logic [7:0] DBG_WPSH         = 8'h20;  // RW inject on DBG_COMMIT: [7:0]=P (NV-BDIZC) [11:8]=SP high nibble (12-bit xt stack)
    localparam logic [7:0] DBG_STAT         = 8'h24;  // R [0]=halted [1]=bkpt_hit [2]=stepping [3]=running
    localparam logic [7:0] DBG_PC           = 8'h28;  // R [15:0]=PC snapshot at the last instruction boundary (coherent when halted = next instruction to execute)
    localparam logic [7:0] DBG_AXYS         = 8'h2C;  // R reg snapshot: [7:0]=A [15:8]=X [23:16]=Y [31:24]=SP(low)
    localparam logic [7:0] DBG_PSH          = 8'h30;  // R snapshot: [7:0]=P [11:8]=SP high nibble
    localparam logic [7:0] DBG_ICNT         = 8'h34;  // R retired-instruction count since SALLYRST (increments on each ST_FETCH boundary)
    localparam logic [7:0] DBG_BEAM         = 8'h38;  // R RESERVED (reads 0 for now): display beam position at the last boundary — [15:0]=scanline [31:16]=beam-x — for future ANTIC/DLI correlation
    localparam logic [7:0] DBG_TRC_CTRL     = 8'h3C;  // RW instruction-trace ring: [0]=enable (capture {PC,A,X,Y,SP,P} every ST_DECODE boundary), [1]=break_on_full (halt the core when the ring wraps). Ring is 4096 deep; readable only when halted (static).
    localparam logic [7:0] DBG_TRC_WPTR     = 8'h40;  // R trace write pointer: [11:0]=next write slot (newest = WPTR-1), [16]=wrapped (ring has been full at least once), [17]=broke_on_full
    localparam logic [7:0] DBG_TRC_IDX      = 8'h44;  // W set the ring read index (0..4095); the entry appears in DBG_TRC_PC/AXYS/P
    localparam logic [7:0] DBG_TRC_PC       = 8'h48;  // R [15:0]=PC of the traced instruction at DBG_TRC_IDX
    localparam logic [7:0] DBG_TRC_AXYS     = 8'h4C;  // R traced regs at DBG_TRC_IDX: [7:0]=A [15:8]=X [23:16]=Y [31:24]=SP(low)
    localparam logic [7:0] DBG_TRC_P        = 8'h50;  // R traced at DBG_TRC_IDX: [7:0]=P [11:8]=SP high nibble
    localparam logic [7:0] DBG_WP           = 8'h54;  // RW [15:0]=data watchpoint address; when armed the core freezes on a bus access to it
    localparam logic [7:0] DBG_WPCFG        = 8'h58;  // RW data watchpoint arm: [0]=enable, [1]=break on WRITE to DBG_WP, [2]=break on READ of DBG_WP (set both for any access)
    localparam logic [7:0] DBG_DIAG         = 8'h5C;  // R debug self-observability (clk_sally, coherent when halted): [1:0]=cfg_s (CDC-synced DBG_CFG), [2]=bkpt_fire seen since arm, [3]=wp_fire seen since arm, [4]=last halt was a watchpoint, [31:16]=bkpt_s (CDC-synced DBG_BKPT — verify it matches what was written)
    localparam logic [7:0] DBG_STRM_CTRL    = 8'h60;  // W FIDELITY streaming-trace control: [0]=strm_en (capture {PC,A,X,Y,SP,P,IR} per instruction into a 4096-deep ring; the core AUTO-HALTS when the ring fills = real stop-the-world), [1]=drain_done (4-phase level handshake: after draining STRM_RD* set this to clear flush_req, reset the ring, and resume the core; then clear it). Rising edge of strm_en resets the ring.
    localparam logic [7:0] DBG_STRM_STAT    = 8'h64;  // R [0]=flush_req: the streaming ring is FULL and the core is halted; the A9 should drain STRM_RD* (0..STRM_WPTR-1) then pulse drain_done
    localparam logic [7:0] DBG_STRM_WPTR    = 8'h68;  // R [12:0]=count of valid entries in the streaming ring (4096 when full; a smaller partial count if strm_en was cleared mid-window)
    localparam logic [7:0] DBG_STRM_RADDR   = 8'h6C;  // W [11:0]=streaming ring read address; the entry appears in STRM_RDLO/RDHI (coherent while flush_req — the ring is static because the core is halted)
    localparam logic [7:0] DBG_STRM_RDLO    = 8'h70;  // R streaming entry [31:0] at STRM_RADDR: [15:0]=PC [23:16]=A [31:24]=X
    localparam logic [7:0] DBG_STRM_RDHI    = 8'h74;  // R streaming entry [63:32] at STRM_RADDR: [7:0]=Y [15:8]=SP [23:16]=P [31:24]=IR

endpackage
`endif
