#!/usr/bin/env python3
"""Extract antic_dmapattern's testdata table into a C header.

ANTIC's per-scanline cycle allocation is the foundation the rest of the ANTIC
suite sits on, and antic_dmapattern carries it AS DATA: one row per
display-list instruction byte, per playfield width, saying cycle by cycle what
the CPU got.  Reading that table is a great deal cheaper than inferring the
schedule one hypothesis at a time, which is what this project has been doing.

Row format (verified against the source):

    dta $<mode>, %<m0>, ... %<m13>, $A5      -- 16 fields: mode, 14 masks, terminator

The blocks are introduced by comments.  There are TWO of them — narrow and
normal — giving 50 rows, which matches the test's own statement that "We have 50
tests to do".  There is no wide-playfield block: wide is covered by
antic_virtdma instead, which is where the extra fetches with nothing to display
are measured.

UNRESOLVED, DELIBERATELY: the exact bit->cycle mapping of the FIRST mask byte.
The ruler comment above each block reads

    0123456  78901234  56789012  34567890  ...

i.e. a 7-wide first group then thirteen 8-wide groups = 111 cycles, while there
are 14 mask bytes = 112 bits.  So one bit of the first byte is padding, and
whether the cycles occupy bits 7..1 or 6..0 is not settled by the ruler alone.
Polarity is likewise not yet proven from first principles, though the evidence
points one way: for a narrow mode-8 line, which fetches very few bytes, the
middle mask bytes are $FF — consistent with 1 = CPU-AVAILABLE (unhalted) rather
than 1 = blocked.  The test's own comment says it walks the mask "counting off
the *unhalted* cycles".

Both questions are settled by reading the scan loop in the test source, and
should be settled there rather than by fitting them to whatever our ANTIC
happens to do.  Until then this emits the RAW bytes and lets the consumer
decide, so no guess is baked into the data.

    tools/acid800_dmatable.py <antic_dmapattern.s> <out.h>
"""
import re
import sys

WIDTHS = ('narrow', 'normal', 'wide')   # 'wide' never appears; kept so a
                                        # future suite revision would be caught


def parse(path):
    """-> [(width, mode_byte, [14 mask bytes])]"""
    rows, width = [], None
    started = False
    for raw in open(path, encoding='latin-1'):
        s = raw.strip()
        if s.startswith('testdata'):
            started = True
            continue
        if not started:
            continue
        if s.startswith(';'):
            for w in WIDTHS:
                if re.search(r'\b%s playfield\b' % w, s):
                    width = w
            continue
        if not s.startswith('dta'):
            continue
        f = [x.strip() for x in s[3:].split(',')]
        if len(f) != 16 or f[-1] != '$A5':
            continue
        if not f[0].startswith('$'):
            continue
        rows.append((width, int(f[0][1:], 16),
                     [int(x[1:], 2) for x in f[1:15]]))
    return rows


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    rows = parse(sys.argv[1])
    with open(sys.argv[2], 'w') as f:
        f.write('/* Generated by tools/acid800_dmatable.py — do not edit.\n'
                ' * ANTIC DMA cycle allocation, extracted from ACID800\n'
                ' * antic_dmapattern\'s testdata table (MIT, Avery Lee).\n'
                ' *\n'
                ' * Each row: the display-list instruction byte, then 14 mask\n'
                ' * bytes walking the scanline.  See the generator for the two\n'
                ' * questions deliberately NOT resolved here (first-byte bit\n'
                ' * alignment, and mask polarity).\n'
                ' */\n'
                '#ifndef ACID_DMATABLE_H\n#define ACID_DMATABLE_H\n\n'
                '#include <stdint.h>\n\n'
                'typedef struct {\n'
                '    const char *width;   /* "narrow" | "normal" | "wide" */\n'
                '    uint8_t     mode;    /* display-list instruction byte */\n'
                '    uint8_t     mask[14];\n'
                '} acid_dma_row;\n\n'
                'static const acid_dma_row acid_dma_rows[] = {\n')
        for w, mode, m in rows:
            f.write('    { "%s", 0x%02X, { %s } },\n'
                    % (w, mode, ', '.join('0x%02X' % b for b in m)))
        f.write('};\n\n#define ACID_DMA_NROWS '
                '((int)(sizeof acid_dma_rows / sizeof acid_dma_rows[0]))\n\n'
                '#endif\n')
    by = {}
    for w, _, _ in rows:
        by[w] = by.get(w, 0) + 1
    print('%d rows: %s' % (len(rows), ', '.join('%s=%d' % kv for kv in by.items())))


if __name__ == '__main__':
    main()
