#!/usr/bin/env python3
"""gen_atari_palette.py — generate hdl/palette/atari_ntsc.hex (256 x RGB888).

The Atari colour byte is hue[7:4] : luma[3:0].  hue 0 = greyscale; hues 1..15
step 24 deg around the NTSC colour wheel.  We build each colour in YIQ (luma +
chroma vector at the hue angle) and convert to RGB with the standard NTSC
matrix.

ALL SIXTEEN LUMINANCES ARE DISTINCT, and that is not a detail.  A COLOUR
REGISTER ignores bit 0 -- gtia_reg_file masks it on the write, which is where
the hardware drops it -- but GTIA MODE 9 does not go through a register: the
screen nibble is dropped straight into the luminance field, which is the whole
reason the mode is "16 shades" when the registers only reach 8.  This table
used to fold bit 0 away, so mode 9 rendered eight shades in pairs: measured
2026-08-18 with tools/gtia_ramp_scene.py (8 colours of 8 px where the mode
promises 16 of 4), and visible in BallBlazer's pre-title screen as pillars
whose dim end collapsed into two shades against the reference's four.

The scale is luma/14, not luma/15, so that every EVEN entry keeps exactly the
RGB it had -- the even codes are the ones a register can produce, they are what
the calibration below was set against, and re-normalising would have quietly
darkened the whole machine by up to 7%.  $xF clamps onto $xE at the top, where
this palette is already clipping.

HUE0 (phase of hue 1) is set so hue 1 = gold and hue 9 = the iconic GR.0 blue.
Prints reference hues so the wheel can be sanity-checked, then writes the hex.

DO NOT "FIX" THIS PALETTE TO MATCH ALTIRRA.  Altirra's default palette renders
hue 1 as olive/yellow-green where ours renders it gold, so BallBlazer's intro
comes out green in the emulator and gold on the board.  GOLD IS CORRECT: hue 1
is "gold" in Atari's own hue table, the intro is documented as a gold title
sequence over a dark reddish ground, and the green appearance is an artifact of
one NTSC decoding model.  This calibration is deliberate; the emulator is the
deviation, not us.  (2026-08-18: measured identical colour registers on both --
PRIOR=$41, COLBK=$10, COLOR0-4 = 28 ca 94 46 10 -- with only the rendered RGB
differing, and nearly changed the wrong side.)

COROLLARY FOR ANY ALTIRRA COMPARISON: compare STRUCTURE AND GEOMETRY, never
colour.  Hue-based detectors will disagree with the reference by design.
"""
import math, argparse, os


def gen(hue0_deg, sat, contrast=1.0):
    pal = []
    for cr in range(256):
        hue = (cr >> 4) & 0xF
        lum = cr & 0xF                 # all 16 levels: mode 9 feeds this directly
        y = min(1.0, lum / 14.0) * contrast
        if hue == 0:
            i = q = 0.0
        else:
            th = math.radians(hue0_deg + (hue - 1) * (360.0 / 15.0))
            i = sat * math.cos(th)
            q = sat * math.sin(th)
        r = y + 0.956 * i + 0.621 * q
        g = y - 0.272 * i - 0.647 * q
        b = y - 1.106 * i + 1.703 * q
        pal.append(tuple(max(0, min(255, round(c * 255))) for c in (r, g, b)))
    return pal


def main():
    ap = argparse.ArgumentParser()
    # 340 is the SHIPPED calibration -- the default has to reproduce the committed
# hex, or a regeneration silently repaints the whole machine.
    ap.add_argument("--hue0", type=float, default=340.0, help="phase of hue 1 (deg)")
    ap.add_argument("--sat",  type=float, default=0.32)
    ap.add_argument("--out",  default=os.path.join(os.path.dirname(__file__),
                                                   "..", "hdl", "palette", "atari_ntsc.hex"))
    ap.add_argument("--write", action="store_true", help="write the hex (else just preview)")
    a = ap.parse_args()
    pal = gen(a.hue0, a.sat)

    names = {1: "gold", 2: "orange", 3: "red-orange", 4: "pink/red", 5: "purple",
             6: "blue-purple", 7: "blue", 8: "blue", 9: "lt-blue (GR.0 bg $94)",
             10: "cyan", 11: "blue-green", 12: "green ($cx text-hue)", 13: "yel-green",
             14: "orange-grn", 15: "lt-orange"}
    print(f"hue0={a.hue0}  sat={a.sat}  (luma 5 row, byte $h A):")
    for h in range(1, 16):
        r, g, b = pal[(h << 4) | 0x0A]
        print(f"  hue {h:2d} ${(h<<4)|0x0a:02x} -> #{r:02x}{g:02x}{b:02x}  {names.get(h,'')}")
    print(f"  KEY: $94 bg=#{pal[0x94][0]:02x}{pal[0x94][1]:02x}{pal[0x94][2]:02x}  "
          f"$ca text=#{pal[0xca][0]:02x}{pal[0xca][1]:02x}{pal[0xca][2]:02x}")

    if a.write:
        with open(a.out, "w") as f:
            f.write("// Atari NTSC hue:luma -> RGB888, generated by tools/gen_atari_palette.py\n")
            f.write(f"// hue0={a.hue0} sat={a.sat}\n")
            for (r, g, b) in pal:
                f.write(f"{r:02x}{g:02x}{b:02x}\n")
        print(f"wrote {a.out}")


if __name__ == "__main__":
    main()
