#!/usr/bin/env python3
"""gen_regmap.py — render the GP0 register map from one spec.

The spec hdl/regmap/xt_gp0.json is the single source of truth for the PL
control-register map over PS GP0.  This renders three artefacts that used to be
hand-mirrored (and therefore drifted):

  hdl/xt_gp0_pkg.sv            SystemVerilog package (block sels + offsets),
                               imported by hdl/xt_gp0_regs.sv
  vitis/xtos/src/xt_gp0_map.h  A9-side C header (block bases + register macros)
  docs/Design/gp0-register-map.md  human-readable table

Usage:
  tools/gen_regmap.py            regenerate all three artefacts in place
  tools/gen_regmap.py --check    regenerate to memory; exit non-zero (and diff)
                                 if any on-disk artefact is stale.  Used by CI.

Stdlib only — no PyYAML dependency (spec is JSON).
"""
import argparse
import difflib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(ROOT, "hdl", "regmap", "xt_gp0.json")

PKG_PATH = os.path.join(ROOT, "hdl", "xt_gp0_pkg.sv")
HDR_PATH = os.path.join(ROOT, "vitis", "xtos", "src", "xt_gp0_map.h")
DOC_PATH = os.path.join(ROOT, "docs", "Design", "gp0-register-map.md")

BANNER = "GENERATED by tools/gen_regmap.py from hdl/regmap/xt_gp0.json — DO NOT EDIT."


def h8(s):
    """Normalise a hex string like '0x40' / '0x3B' to an 8-bit Verilog/C literal value."""
    return int(str(s), 16)


def load_spec():
    with open(SPEC) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# SystemVerilog package
# ---------------------------------------------------------------------------
def render_pkg(spec):
    L = []
    L.append(f"// xt_gp0_pkg.sv — {BANNER}")
    L.append("//")
    L.append("// Block selectors (addr[11:8]) and per-block register offsets (addr[7:0])")
    L.append("// for the GP0 control-register file.  Imported by xt_gp0_regs.sv so the RTL")
    L.append("// decode and the A9-side xt_gp0_map.h cannot drift.")
    L.append("`ifndef XT_GP0_PKG_SV")
    L.append("`define XT_GP0_PKG_SV")
    L.append("package xt_gp0_pkg;")
    L.append("")
    L.append("    // ---- block selectors = " + spec["sel_field"] + " ----")
    for b in spec["blocks"]:
        L.append(f"    localparam logic [3:0] {b['sv_sel']:<12} = 4'h{h8(b['sel']):X};"
                 f"  // {b['base']}  {b['name']}")
    L.append("")
    L.append("    // ---- register offsets = " + spec["off_field"] + " (per block) ----")
    for b in spec["blocks"]:
        rngs = b.get("ranges", [])
        regs = b.get("regs", [])
        if not rngs and not regs:
            continue
        L.append(f"    // {b['name']}")
        for r in rngs:
            L.append(f"    localparam logic [7:0] {r['sv_lo']:<16} = 8'h{h8(r['lo']):02X};"
                     f"  // {r['access']} {r['desc']}")
            L.append(f"    localparam logic [7:0] {r['sv_hi']:<16} = 8'h{h8(r['hi']):02X};")
        for r in regs:
            L.append(f"    localparam logic [7:0] {r['sv']:<16} = 8'h{h8(r['off']):02X};"
                     f"  // {r['access']} {r['desc']}")
    L.append("")
    L.append("endpackage")
    L.append("`endif")
    L.append("")
    return "\n".join(L)


# ---------------------------------------------------------------------------
# C header
# ---------------------------------------------------------------------------
def render_hdr(spec):
    L = []
    L.append(f"/* xt_gp0_map.h — {BANNER}")
    L.append(" *")
    L.append(" * The PL control-register map over PS GP0 (@ " + spec["base"] + ").")
    L.append(" * Single source of truth: hdl/regmap/xt_gp0.json (mirrors the hardware")
    L.append(" * decode in hdl/xt_gp0_regs.sv via the generated hdl/xt_gp0_pkg.sv).")
    L.append(" *")
    for n in spec.get("notes", []):
        L.append(f" *   {n}")
    L.append(" *")
    for b in spec["blocks"]:
        L.append(f" *   {b['base']}  {b['name']:<11} {b['desc']}")
    L.append(" */")
    L.append("#ifndef XT_GP0_MAP_H_")
    L.append("#define XT_GP0_MAP_H_")
    L.append("")
    L.append("#ifndef " + spec["base_macro"])
    L.append(f"#define {spec['base_macro']:<16} {spec['base']}u")
    L.append("#endif")
    L.append("")
    L.append("/* ---- per-device block bases --------------------------------------------- */")
    for b in spec["blocks"]:
        L.append(f"#define {b['base_macro']:<16} ({spec['base_macro']} + {b['base']}u)")
    L.append("")
    for b in spec["blocks"]:
        rngs = b.get("ranges", [])
        regs = b.get("regs", [])
        if not rngs and not regs:
            continue
        L.append(f"/* ---- {b['name']} block --------------------------------------------------- */")
        for r in rngs:
            L.append(f"/*   {r['lo']}..{r['hi']}  {r['access']}  {r['desc']} */")
        for r in regs:
            macro = r["c"]
            expr = f"({b['base_macro']} + 0x{h8(r['off']):02X}u)"
            L.append(f"#define {macro:<20} {expr:<28} /* {r['access']} {r['desc']} */")
        L.append("")
    L.append("#endif /* XT_GP0_MAP_H_ */")
    L.append("")
    return "\n".join(L)


# ---------------------------------------------------------------------------
# Docs table
# ---------------------------------------------------------------------------
def render_doc(spec):
    L = []
    L.append(f"<!-- {BANNER} -->")
    L.append("# GP0 register map")
    L.append("")
    L.append(f"PL control registers over PS GP0, base `{spec['base']}`. Block selector = "
             f"`{spec['sel_field']}`, offset = `{spec['off_field']}`.")
    L.append("")
    for n in spec.get("notes", []):
        L.append(f"- {n}")
    L.append("")
    for b in spec["blocks"]:
        L.append(f"## {b['base']} — {b['name']}  (`{b['base_macro']}`)")
        L.append("")
        L.append(b["desc"])
        L.append("")
        L.append("| Offset | Acc | Width | C macro | SV | Meaning |")
        L.append("|--------|-----|-------|---------|----|---------|")
        for r in b.get("ranges", []):
            L.append(f"| {r['lo']}..{r['hi']} | {r['access']} | — | (range) | "
                     f"`{r['sv_lo']}`/`{r['sv_hi']}` | {r['desc']} |")
        for r in b.get("regs", []):
            L.append(f"| {r['off']} | {r['access']} | {r['width']} | `{r['c']}` | "
                     f"`{r['sv']}` | {r['desc']} |")
        L.append("")
    return "\n".join(L)


ARTEFACTS = [
    (PKG_PATH, render_pkg),
    (HDR_PATH, render_hdr),
    (DOC_PATH, render_doc),
]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail (with a diff) if any artefact is stale; do not write")
    args = ap.parse_args()

    spec = load_spec()
    stale = []
    for path, render in ARTEFACTS:
        want = render(spec)
        if args.check:
            have = ""
            if os.path.exists(path):
                with open(path) as f:
                    have = f.read()
            if have != want:
                stale.append(path)
                rel = os.path.relpath(path, ROOT)
                sys.stderr.write(f"STALE: {rel}\n")
                sys.stderr.writelines(difflib.unified_diff(
                    have.splitlines(keepends=True), want.splitlines(keepends=True),
                    fromfile=rel + " (on disk)", tofile=rel + " (regenerated)"))
        else:
            with open(path, "w") as f:
                f.write(want)
            print(f"wrote {os.path.relpath(path, ROOT)}")

    if args.check:
        if stale:
            sys.stderr.write(
                f"\n{len(stale)} artefact(s) stale — run tools/gen_regmap.py and commit.\n")
            return 1
        print("regmap: all generated artefacts up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
