/* xt_gp0_map.h — GENERATED by tools/gen_regmap.py from hdl/regmap/xt_gp0.json — DO NOT EDIT.
 *
 * The PL control-register map over PS GP0 (@ 0x43C00000).
 * Single source of truth: hdl/regmap/xt_gp0.json (mirrors the hardware
 * decode in hdl/xt_gp0_regs.sv via the generated hdl/xt_gp0_pkg.sv).
 *
 *   The slave claims 0x000..0xFFF (addr[15:12]==0); sally_rom_loader OR-muxes at 0x1000+.
 *   Every register is 32-bit word-aligned (Xil_In32/Out32, no byte-lane tricks); reads never alias writes.
 *   Runs on clk_sys (same domain as the blitter) — no CDC on the register bus.
 *
 *   0x000  BLITTER     blit regs (offset = bl_addr) + STATUS/SEQ reads; dual-access 6502 $D4Bx/$D4Cx/$D4Ex under UNLK_BLIT
 *   0x100  SPRITE      sprite-engine reg index/data port; dual-access 6502 $D4Ax/$D4Dx under UNLK_SPRITE
 *   0x200  COMP        drag-overlay config (A9-only, whole 32-bit words)
 *   0x300  CTRL        control plane (gp0_ctrl, SALLY speed, XT unlock, keyboard inject)
 *   0x400  DIAG        PL diagnostic words (A9-only, read-only, word-aligned)
 *   0x500  XLCTL       XL compositor-plane window placement (A9-positioned emulation window)
 *   0x600  MATH        math-coprocessor mailbox (A9-only); 6502 side = $D5C6-$D5C8 + the $4000-$5FFF math page
 *   0x700  TRNG        hardware entropy (ring-oscillator TRNG in the PL; A9-only, read-only)
 *   0x800  DEBUG       in-fabric 6502 debugger (xt6502_debug): halt/step/breakpoint/register access, driving /bin/6502. Halt is a non-destructive rdy-gate (state preserved); all actions align to the ST_FETCH instruction boundary. Status is coherent when halted (a halted core is static). Sel 0x9 is RESERVED for the future ANTIC debugger. See docs/OS/6502-debug.md
 */
#ifndef XT_GP0_MAP_H_
#define XT_GP0_MAP_H_

#ifndef XT_GP0_BASE
#define XT_GP0_BASE      0x43C00000u
#endif

/* ---- per-device block bases --------------------------------------------- */
#define XT_BLK_BLITTER   (XT_GP0_BASE + 0x000u)
#define XT_BLK_SPRITE    (XT_GP0_BASE + 0x100u)
#define XT_BLK_COMP      (XT_GP0_BASE + 0x200u)
#define XT_BLK_CTRL      (XT_GP0_BASE + 0x300u)
#define XT_BLK_DIAG      (XT_GP0_BASE + 0x400u)
#define XT_BLK_XLCTL     (XT_GP0_BASE + 0x500u)
#define XT_BLK_MATH      (XT_GP0_BASE + 0x600u)
#define XT_BLK_TRNG      (XT_GP0_BASE + 0x700u)
#define XT_BLK_DEBUG     (XT_GP0_BASE + 0x800u)

/* ---- BLITTER block --------------------------------------------------- */
/*   0x00..0x18  W  blitter registers DST/PAT/CMD/SRC/FLAGS (bl_addr = offset); see blitter.h XT_BL_* */
/*   0x30..0x3B  W  SRC/DST DDR-surface descriptors / ROW0 bases (bl_addr = offset) */
#define XT_BLT_STATUS        (XT_BLK_BLITTER + 0x40u)     /* R {pat_blocked[2], queue_full[1], busy[0]} */
#define XT_BLT_SEQ           (XT_BLK_BLITTER + 0x44u)     /* R seq_counter[15:0] */

/* ---- SPRITE block --------------------------------------------------- */
#define XT_SPR_IDX           (XT_BLK_SPRITE + 0x00u)      /* W latch sprite reg index */
#define XT_SPR_DATA          (XT_BLK_SPRITE + 0x04u)      /* W sprite reg data + strobe (writes idx/data to engine) */
#define XT_SPR_COLL          (XT_BLK_SPRITE + 0x08u)      /* R collision[col_sel] (set col_sel first via $D4D9); [15:0] = sprites this one hit */

/* ---- COMP block --------------------------------------------------- */
#define XT_OVL_EN            (XT_BLK_COMP + 0x00u)        /* W [0]=enable; also toggles the commit flag */
#define XT_OVL_BASE          (XT_BLK_COMP + 0x04u)        /* W DDR byte address (32-bit) */
#define XT_OVL_X             (XT_BLK_COMP + 0x08u)        /* W on-screen X (12-bit) */
#define XT_OVL_Y             (XT_BLK_COMP + 0x0Cu)        /* W on-screen Y (12-bit) */
#define XT_OVL_W             (XT_BLK_COMP + 0x10u)        /* W width px (12-bit; stride = w<<2) */
#define XT_OVL_H             (XT_BLK_COMP + 0x14u)        /* W height px (12-bit) */

/* ---- CTRL block --------------------------------------------------- */
#define XT_CTRL_GP0          (XT_BLK_CTRL + 0x00u)        /* RW [0]=bars, [3:1]=XL scale, [4]=DMACTL-blank, [5]=video-sleep (gate clk_pix off) (A9-only); read = effective */
#define XT_CTRL_SPEED        (XT_BLK_CTRL + 0x04u)        /* RW SALLY clock_mult (dual: 6502 $D4CA); read = effective. W -> bl_addr $D4CA */
#define XT_CTRL_UNLOCK       (XT_BLK_CTRL + 0x08u)        /* RW XT register-unlock (dual: 6502 $D1DF); read = effective */
#define XT_CTRL_KBD_INJECT   (XT_BLK_CTRL + 0x0Cu)        /* W KBCODE + POKEY IRQ (A9-only; emits $D4CF) */
#define XT_CTRL_KBD_RELEASE  (XT_BLK_CTRL + 0x10u)        /* W all-keys-up (A9-only; emits $D4CD) */
#define XT_CTRL_KBD_BREAK    (XT_BLK_CTRL + 0x14u)        /* W Atari BREAK (A9-only; emits $D4CB) */
#define XT_CTRL_CMPCFG       (XT_BLK_CTRL + 0x18u)        /* RW compositor plane arrangement (A9-only; reset 0x210 = current). depth: [3:0]=desktop, [7:4]=overlay, [11:8]=XL. alpha_en: [16]=desktop, [17]=overlay, [18]=XL. Route-A flip = desktop on top with alpha (0x00010132) */
#define XT_CTRL_SALLYRST     (XT_BLK_CTRL + 0x1Cu)        /* RW [0]=1 HOLD the SALLY realm in reset (A9-only; reset 0 = running). Cold-boot-per-launch: hold, rewrite the OS/RAM through the ROM-loader window (0x1000+), release = fresh coldstart. Resets the 6502 core AND the XT state a stock guest cannot know about (bank selects $D5C0/$D5C1, screen banking $D5C3-5); the video pipeline keeps scanning */
#define XT_CTRL_JOY_OVR      (XT_BLK_CTRL + 0x20u)        /* W keypad->joystick override (A9-only; forces STICK0/1 PORTA pins + TRIG0 when the physical PCAL9722 joystick is absent). [31]=override enable (0 = joy_bridge/PCAL9722 drives as normal). [7:0]=PORTA pin value, ACTIVE-LOW (STICK0 bits[3:0]: bit0=up bit1=down bit2=left bit3=right; STICK1 bits[7:4]; 1=released 0=pressed; 0xFF=neutral). [8]=TRIG0/fire value, ACTIVE-LOW (0=fire pressed). Muxed into pia_regs PORTA + GTIA TRIG0 in antic_top; the joy_bridge write-through path is untouched */
#define XT_CTRL_CONSOL       (XT_BLK_CTRL + 0x24u)        /* W console-keys value the 6502 reads as CONSOL ($D01F). ACTIVE-LOW: bit0=START bit1=SELECT bit2=OPTION (0=pressed). Reset $07 (none). The kernel holds OPTION ($03) across a game coldstart so the XL OS leaves BASIC DISABLED ($A000-$BFFF stays RAM) — no game boots with BASIC mapped, and BASIC shadowing RAM was crashing games; releases to $07 for boot-to-BASIC (READY). Replaces the hardwired 8'h07 in antic_top */

/* ---- DIAG block --------------------------------------------------- */
#define XT_DIAG0             (XT_BLK_DIAG + 0x00u)        /* R MMCM locks / clk_pix-alive / frame count */
#define XT_DIAG2             (XT_BLK_DIAG + 0x04u)        /* R production-chain counters */
#define XT_DIAG3             (XT_BLK_DIAG + 0x08u)        /* R read-path activity */
#define XT_DIAG4             (XT_BLK_DIAG + 0x0Cu)        /* R HP3 (XL) first-AR address */
#define XT_DIAG5             (XT_BLK_DIAG + 0x10u)        /* R HP0 (desktop) first-AR address */
#define XT_DIAG6             (XT_BLK_DIAG + 0x14u)        /* R HP2 read-probe status */
#define XT_DIAG7             (XT_BLK_DIAG + 0x18u)        /* R HP2 read-probe last rdata */
#define XT_DIAG8             (XT_BLK_DIAG + 0x1Cu)        /* R TEMP ROM-window upload diag: [31:16]=window AXI writes accepted, [15:0]=rom_we pulses emitted to sally_mem */
#define XT_DIAG9             (XT_BLK_DIAG + 0x20u)        /* R TEMP ROM-window upload diag: [23:8]=last rom_addr, [7:0]=last rom_data */

/* ---- XLCTL block --------------------------------------------------- */
#define XT_XL_WIN_X          (XT_BLK_XLCTL + 0x00u)       /* W plane origin X on screen (12-bit) */
#define XT_XL_WIN_Y          (XT_BLK_XLCTL + 0x04u)       /* W plane origin Y on screen (12-bit) */
#define XT_XL_WIN_W          (XT_BLK_XLCTL + 0x08u)       /* W clip width  (12-bit; clip_x1 = X + W) */
#define XT_XL_WIN_H          (XT_BLK_XLCTL + 0x0Cu)       /* W clip height (12-bit; clip_y1 = Y + H) */
#define XT_XL_WIN_SCALE      (XT_BLK_XLCTL + 0x10u)       /* W integer scale 1..5 */
#define XT_XL_WIN_EN         (XT_BLK_XLCTL + 0x14u)       /* W [0]=1: use these regs (A9-positioned); 0: legacy gp0_ctrl-scale centred */

/* ---- MATH block --------------------------------------------------- */
#define XT_MATH_EVT          (XT_BLK_MATH + 0x00u)        /* R doorbell event pop: [8]=valid, [7:0]=chunk index; a read consumes one event; IRQ_F2P[1] level = FIFO non-empty */
#define XT_MATH_DONE         (XT_BLK_MATH + 0x04u)        /* W completion: [7:0]=chunk, [15:8]=result-span first line (64 B lines), [23:16]=line count; reloads the span into the math page if that chunk is resident, then raises $D5C7 done */
#define XT_MATH_STAT         (XT_BLK_MATH + 0x08u)        /* R [0]=engine busy, [1]=chunk resident/ready, [2]=evt FIFO non-empty, [15:8]=resident chunk, [23:16]=evt FIFO fill */

/* ---- TRNG block --------------------------------------------------- */
#define XT_TRNG_RND          (XT_BLK_TRNG + 0x00u)        /* R whitened 32-bit entropy word (free-running pool snapshot); read repeatedly for fresh words. Entropy SOURCE for the OS pool, not raw crypto output */

/* ---- DEBUG block --------------------------------------------------- */
#define XT_DBG_HALT          (XT_BLK_DEBUG + 0x00u)       /* W write (any) -> run to the next instruction boundary, then freeze (state preserved). Also arms halt-at-reset when combined with a SALLYRST pulse */
#define XT_DBG_GO            (XT_BLK_DEBUG + 0x04u)       /* W write (any) -> release the core, run at the configured speed */
#define XT_DBG_STEP          (XT_BLK_DEBUG + 0x08u)       /* W write N -> execute exactly N instructions (min 1) then freeze */
#define XT_DBG_CFG           (XT_BLK_DEBUG + 0x0Cu)       /* RW [0]=bkpt_en (arm the PC breakpoint), [1]=halt_at_reset (freeze at the reset-vector fetch after the next SALLYRST release) */
#define XT_DBG_BKPT          (XT_BLK_DEBUG + 0x10u)       /* RW [15:0]=breakpoint PC; when bkpt_en, the core freezes at the ST_FETCH of this address (before executing it) */
#define XT_DBG_COMMIT        (XT_BLK_DEBUG + 0x14u)       /* W write (any) -> inject DBG_WPC/WAXYS/WPSH into the core's PC/regs and re-anchor at ST_FETCH (only meaningful while halted) */
#define XT_DBG_WPC           (XT_BLK_DEBUG + 0x18u)       /* RW [15:0]=PC to inject on DBG_COMMIT */
#define XT_DBG_WAXYS         (XT_BLK_DEBUG + 0x1Cu)       /* RW regs to inject on DBG_COMMIT: [7:0]=A [15:8]=X [23:16]=Y [31:24]=SP(low) */
#define XT_DBG_WPSH          (XT_BLK_DEBUG + 0x20u)       /* RW inject on DBG_COMMIT: [7:0]=P (NV-BDIZC) [11:8]=SP high nibble (12-bit xt stack) */
#define XT_DBG_STAT          (XT_BLK_DEBUG + 0x24u)       /* R [0]=halted [1]=bkpt_hit [2]=stepping [3]=running */
#define XT_DBG_PC            (XT_BLK_DEBUG + 0x28u)       /* R [15:0]=PC snapshot at the last instruction boundary (coherent when halted = next instruction to execute) */
#define XT_DBG_AXYS          (XT_BLK_DEBUG + 0x2Cu)       /* R reg snapshot: [7:0]=A [15:8]=X [23:16]=Y [31:24]=SP(low) */
#define XT_DBG_PSH           (XT_BLK_DEBUG + 0x30u)       /* R snapshot: [7:0]=P [11:8]=SP high nibble */
#define XT_DBG_ICNT          (XT_BLK_DEBUG + 0x34u)       /* R retired-instruction count since SALLYRST (increments on each ST_FETCH boundary) */
#define XT_DBG_BEAM          (XT_BLK_DEBUG + 0x38u)       /* R RESERVED (reads 0 for now): display beam position at the last boundary — [15:0]=scanline [31:16]=beam-x — for future ANTIC/DLI correlation */
#define XT_DBG_TRC_CTRL      (XT_BLK_DEBUG + 0x3Cu)       /* RW instruction-trace ring: [0]=enable (capture {PC,A,X,Y,SP,P} every ST_DECODE boundary), [1]=break_on_full (halt the core when the ring wraps). Ring is 4096 deep; readable only when halted (static). */
#define XT_DBG_TRC_WPTR      (XT_BLK_DEBUG + 0x40u)       /* R trace write pointer: [11:0]=next write slot (newest = WPTR-1), [16]=wrapped (ring has been full at least once), [17]=broke_on_full */
#define XT_DBG_TRC_IDX       (XT_BLK_DEBUG + 0x44u)       /* W set the ring read index (0..4095); the entry appears in DBG_TRC_PC/AXYS/P */
#define XT_DBG_TRC_PC        (XT_BLK_DEBUG + 0x48u)       /* R [15:0]=PC of the traced instruction at DBG_TRC_IDX */
#define XT_DBG_TRC_AXYS      (XT_BLK_DEBUG + 0x4Cu)       /* R traced regs at DBG_TRC_IDX: [7:0]=A [15:8]=X [23:16]=Y [31:24]=SP(low) */
#define XT_DBG_TRC_P         (XT_BLK_DEBUG + 0x50u)       /* R traced at DBG_TRC_IDX: [7:0]=P [11:8]=SP high nibble */
#define XT_DBG_WP            (XT_BLK_DEBUG + 0x54u)       /* RW [15:0]=data watchpoint address; when armed the core freezes on a bus access to it */
#define XT_DBG_WPCFG         (XT_BLK_DEBUG + 0x58u)       /* RW data watchpoint arm: [0]=enable, [1]=break on WRITE to DBG_WP, [2]=break on READ of DBG_WP (set both for any access) */
#define XT_DBG_DIAG          (XT_BLK_DEBUG + 0x5Cu)       /* R debug self-observability (clk_sally, coherent when halted): [1:0]=cfg_s (CDC-synced DBG_CFG), [2]=bkpt_fire seen since arm, [3]=wp_fire seen since arm, [4]=last halt was a watchpoint, [31:16]=bkpt_s (CDC-synced DBG_BKPT — verify it matches what was written) */
#define XT_DBG_STRM_CTRL     (XT_BLK_DEBUG + 0x60u)       /* W FIDELITY streaming-trace control: [0]=strm_en (capture {PC,A,X,Y,SP,P,IR} per instruction into a 4096-deep ring; the core AUTO-HALTS when the ring fills = real stop-the-world), [1]=drain_done (4-phase level handshake: after draining STRM_RD* set this to clear flush_req, reset the ring, and resume the core; then clear it). Rising edge of strm_en resets the ring. */
#define XT_DBG_STRM_STAT     (XT_BLK_DEBUG + 0x64u)       /* R [0]=flush_req: the streaming ring is FULL and the core is halted; the A9 should drain STRM_RD* (0..STRM_WPTR-1) then pulse drain_done */
#define XT_DBG_STRM_WPTR     (XT_BLK_DEBUG + 0x68u)       /* R [12:0]=count of valid entries in the streaming ring (4096 when full; a smaller partial count if strm_en was cleared mid-window) */
#define XT_DBG_STRM_RADDR    (XT_BLK_DEBUG + 0x6Cu)       /* W [11:0]=streaming ring read address; the entry appears in STRM_RDLO/RDHI (coherent while flush_req — the ring is static because the core is halted) */
#define XT_DBG_STRM_RDLO     (XT_BLK_DEBUG + 0x70u)       /* R streaming entry [31:0] at STRM_RADDR: [15:0]=PC [23:16]=A [31:24]=X */
#define XT_DBG_STRM_RDHI     (XT_BLK_DEBUG + 0x74u)       /* R streaming entry [63:32] at STRM_RADDR: [7:0]=Y [15:8]=SP [23:16]=P [31:24]=IR */

#endif /* XT_GP0_MAP_H_ */
